(()=>{'use strict';
const K={products:'mingus_v3_products',orders:'mingus_v3_orders',last:'mingus_v3_last',session:'mingus_v3_admin',history:'mingos_cash_history',goal:'mingos_daily_goal',flash:'mingos_flash_deal',operation:'mingos_operation',ingredients:'mingos_paused_ingredients'};
const defaultOperation={openHour:'11:00',closeHour:'23:00',accepting:true,deliveryEnabled:true,pickupEnabled:true,kitchenLoad:'normal',pickupMinutes:'15–25',deliveryMinutes:'30–45',minimumOrder:18,payments:{pix:true,card:true,cash:true},changeMode:'normal',neighborhoods:[{name:'Centro',fee:5.9},{name:'Barra',fee:7.9},{name:'Zona Nova',fee:6.9},{name:'Indianópolis',fee:8.9},{name:'Nova Tramandaí',fee:9.9},{name:'Imbé',fee:11.9}]};
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=n=>(+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const $=s=>document.querySelector(s),statuses=[['pending_acceptance','Aguardando aceite'],['accepted','Aceitos'],['preparing','Em preparo'],['ready','Prontos'],['delivering','Em entrega'],['completed','Finalizados']];
const beverageSeeds=[
 {id:'refri600',cat:'bebidas',name:'Refrigerante 600 ml',desc:'Ideal para acompanhar um pastel caprichado.',price:9.9,img:'produto-refrigerante.jpg',tag:'Na medida',opts:[],available:true},
 {id:'refri2l',cat:'bebidas',name:'Refrigerante 2 litros',desc:'Cola ou guaraná para compartilhar.',price:14.9,img:'produto-refrigerante.jpg',tag:'Para dividir',opts:[],available:true},
 {id:'agua',cat:'bebidas',name:'Água mineral 500 ml',desc:'Sem gás, leve e bem gelada.',price:4,img:'produto-refrigerante.jpg',tag:'Refrescante',opts:[],available:true},
 {id:'aguagas',cat:'bebidas',name:'Água com gás 500 ml',desc:'Gelada, com borbulhas e muito frescor.',price:5,img:'produto-refrigerante.jpg',tag:'Leve',opts:[],available:true},
 {id:'suco',cat:'bebidas',name:'Suco natural 500 ml',desc:'Laranja ou maracujá, feito para refrescar.',price:11.9,img:'produto-refrigerante.jpg',tag:'Natural',opts:[],available:true},
 {id:'energetico',cat:'bebidas',name:'Energético 250 ml',desc:'Lata gelada para recarregar o dia.',price:12.9,img:'produto-refrigerante.jpg',tag:'Energia',opts:[],available:true},
 {id:'cha',cat:'bebidas',name:'Chá gelado 450 ml',desc:'Limão ou pêssego, suave e refrescante.',price:8.9,img:'produto-refrigerante.jpg',tag:'Verão',opts:[],available:true}
];
const acaiSeedOptions=[{name:'Bases',max:1,items:['Açaí Tradicional','Açaí com Cupuaçu','Creme de Pitaya','Misto Açaí + Cupuaçu']},{name:'Complementos inclusos',max:4,items:['Banana','Morango','Kiwi','Manga','Uva','Granola','Leite em pó','Paçoca','Coco ralado','Chocoball','Flocos de arroz','Amendoim']},{name:'Adicionais premium',max:12,items:['Nutella|5','Creme de Ninho|4.5','Morango extra|4','Ouro Branco|4.5','Bis|3.5','KitKat|4.5','Brownie|5','Doce de leite|3.5','Leite condensado extra|2.5','M&M’s|4.5']}],pastelSeedOptions=[{name:'Acréscimos',max:2,items:['Borda recheada de Catupiry|4','Dobro de Queijo|3']},{name:'Retiradas',max:3,items:['Sem Cebola','Sem Azeitona','Sem Milho']},{name:'Preparo',max:1,items:['Frito','Assado']}];
beverageSeeds.push(
 {id:'a300',cat:'acai',name:'Açaí 300 ml',desc:'Açaí cremoso + até 4 adicionais à escolha.',price:16.9,img:'produto-acai-300.jpg',tag:'Leve',opts:acaiSeedOptions,available:true},{id:'a500',cat:'acai',name:'Açaí 500 ml',desc:'A medida favorita + até 4 adicionais.',price:22.9,img:'produto-acai-500.jpg',tag:'Mais pedido',opts:acaiSeedOptions,available:true},{id:'a700',cat:'acai',name:'Açaí 700 ml',desc:'Generoso, gelado e montado do seu jeito.',price:29.9,img:'produto-acai-700.jpg',tag:'Tamanho fome',opts:acaiSeedOptions,available:true},{id:'a1l',cat:'acai',name:'Barca 1 litro',desc:'Para compartilhar com complementos caprichados.',price:42.9,img:'produto-barca-acai.jpg',tag:'Para dividir',opts:acaiSeedOptions,available:true},
 {id:'pcarne',cat:'pasteis',name:'Carne da casa',desc:'Carne temperada, cebola e cheiro-verde.',price:14.9,img:'produto-pastel-carne.jpg',tag:'Clássico',opts:pastelSeedOptions,available:true},{id:'pqueijo',cat:'pasteis',name:'Queijo puxa-puxa',desc:'Muçarela generosa e orégano.',price:13.9,img:'produto-pastel-queijo.jpg',tag:'Favorito',opts:pastelSeedOptions,available:true},{id:'pfrango',cat:'pasteis',name:'Frango cremoso',desc:'Frango desfiado, milho e catupiry.',price:16.9,img:'produto-pastel-frango.jpg',tag:'Cremoso',opts:pastelSeedOptions,available:true},{id:'ppizza',cat:'pasteis',name:'Pizza de feira',desc:'Queijo, presunto, tomate e orégano.',price:15.9,img:'produto-pastel-pizza.jpg',tag:'Nostalgia',opts:pastelSeedOptions,available:true},{id:'pdocel',cat:'pasteis',name:'Doce de leite',desc:'Crocante por fora, cremoso por dentro.',price:15.9,img:'produto-pastel-doce.jpg',tag:'Doce',opts:pastelSeedOptions,available:true},
 {id:'combo',cat:'combos',name:'Dupla Mingos',desc:'Dois pastéis clássicos + duas bebidas.',price:39.9,img:'produto-combo-dupla.jpg',tag:'Economize',opts:[],available:true},{id:'combo2',cat:'combos',name:'Verão completo',desc:'Dois pastéis + açaí 500 ml.',price:49.9,img:'produto-combo-verao.jpg',tag:'Combo',opts:[],available:true},{id:'refri',cat:'bebidas',name:'Refrigerante lata 350 ml',desc:'Cola, guaraná ou laranja bem gelado.',price:6.5,img:'produto-refrigerante.jpg',tag:'Gelado',opts:[],available:true}
);
async function audit(action,details={}){try{const firebase=await window.MingosSync.waitFirebase();await firebase.saveDocument('audit',`log-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,{action,details,createdAt:new Date().toISOString(),adminUid:firebase.ADMIN_UID})}catch(error){console.warn('Auditoria indisponível',error)}}
let orders=[],products=[],history=[],contacts=[],orderQuery='',productQuery='',contactQuery='',peakChart=null,flashTimer=null,unsubscribeOrders=null,catalogSeeded=false;
const login=$('#login'),app=$('#app'),orderModal=$('#order-modal'),productModal=$('#product-modal'),closeModal=$('#close-day-modal');
const optionsField=document.createElement('label');optionsField.innerHTML='Grupos de opções<textarea id="prod-options" rows="6" placeholder="Bases | 1 | Açaí Tradicional; Açaí com Cupuaçu\nComplementos inclusos | 4 | Banana; Morango; Granola\nAdicionais premium | 12 | Nutella|5; Brownie|5"></textarea><small>Uma linha por grupo: nome | limite | itens separados por ponto e vírgula. Para item pago use Nome|Preço.</small>';$('#product-form button.primary').before(optionsField);
const scheduleField=document.createElement('div');scheduleField.className='row';scheduleField.innerHTML='<label>Exibir a partir de<input id="prod-from" type="time"></label><label>Ocultar depois de<input id="prod-until" type="time"></label>';$('#product-form button.primary').before(scheduleField);
const optionsToText=groups=>(groups||[]).map(group=>`${group.name} | ${group.max} | ${(group.items||[]).join('; ')}`).join('\n');
const parseOptions=text=>String(text||'').split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const parts=line.split(' | ');return{name:(parts.shift()||'Opções').trim(),max:Math.max(1,Number(parts.shift())||1),items:parts.join(' | ').split(';').map(item=>item.trim()).filter(Boolean)}}).filter(group=>group.items.length);
$('#settings .settings-grid').insertAdjacentHTML('beforeend','<article class="settings-card"><span class="settings-icon">🥝</span><h2>Ingredientes pausados</h2><p>Digite um ingrediente por linha. Ele some imediatamente das personalizações.</p><label>Indisponíveis hoje<textarea id="paused-ingredients" rows="6" placeholder="Morango\nNutella"></textarea></label><button class="primary" id="save-ingredients">Publicar ingredientes</button></article>');
$('#settings .settings-grid').insertAdjacentHTML('beforeend','<article class="settings-card"><span class="settings-icon">☎</span><h2>WhatsApp oficial</h2><p>Número que receberá a cópia do pedido, com país e DDD.</p><label>Número<input id="store-whatsapp" inputmode="numeric" placeholder="5551999999999"></label><button class="primary" id="save-contact">Salvar WhatsApp</button></article>');
$('#settings .settings-grid').insertAdjacentHTML('beforeend','<article class="settings-card"><span class="settings-icon">%</span><h2>Cupom de desconto</h2><p>Crie ou atualize um cupom válido imediatamente.</p><div class="row"><label>Código<input id="coupon-code" placeholder="MINGOS10"></label><label>Desconto %<input id="coupon-percent" type="number" min="1" max="70" value="10"></label></div><label>Pedido mínimo<input id="coupon-minimum" type="number" min="0" value="0"></label><button class="primary" id="save-coupon">Publicar cupom</button></article>');
$('#settings .settings-grid').insertAdjacentHTML('beforeend','<article class="settings-card"><span class="settings-icon">🛵</span><h2>Meta de frete grátis</h2><p>Defina o subtotal necessário para zerar a entrega.</p><label>Valor mínimo<input id="free-delivery-minimum" type="number" min="0" step="1" value="65"></label><button class="primary" id="save-delivery-rule">Publicar regra</button></article>');
function toast(msg){const t=$('#admin-toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2800)}
async function enter(){login.hidden=true;app.hidden=false;sync();try{const firebase=await window.MingosSync.waitFirebase();unsubscribeOrders=await window.MingosSync.watchAdminOrders(next=>{const previous=new Set(orders.map(order=>order.id));orders=next.map(order=>order.status==='received'?{...order,status:'pending_acceptance'}:order);const incoming=orders.find(order=>order.status==='pending_acceptance'&&!previous.has(order.id));if(incoming){successSound();toast(`Novo pedido #${incoming.code} aguardando aceite`)}renderOrders()},error=>{console.error(error);toast(error.friendlyMessage||'Erro ao receber pedidos')});firebase.watchCollection('products',next=>{const missing=beverageSeeds.filter(seed=>!next.some(product=>product.id===seed.id));products=[...next,...missing];write(K.products,products);renderProducts();if(missing.length&&!catalogSeeded){catalogSeeded=true;Promise.all(missing.map(product=>firebase.saveDocument('products',product.id,product))).then(()=>toast(`${missing.length} novas bebidas publicadas`)).catch(error=>console.error('Falha ao publicar bebidas',error))}});firebase.watchCollection('leads',next=>{contacts=next.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));renderContacts()});firebase.watchCollection('cashHistory',next=>{history=next.sort((a,b)=>new Date(b.closedAt)-new Date(a.closedAt));write(K.history,history);renderHistory()});firebase.watchCollection('settings',next=>{next.forEach(setting=>{if(setting.id==='goal')write(K.goal,setting.value);if(setting.id==='flash')write(K.flash,setting.value);if(setting.id==='operation')write(K.operation,setting.value)});renderAll()})}catch(error){console.error(error);toast(error.friendlyMessage||'Sem conexão com o Firebase')}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#login-error').textContent='Conectando…';try{await window.MingosSync.adminLogin($('#user').value.trim(),$('#pass').value);sessionStorage.setItem(K.session,'ok');$('#login-error').textContent='';await enter()}catch(error){console.error(error);const firebase=await window.MingosSync.waitFirebase().catch(()=>null);$('#login-error').textContent=firebase?.friendlyError(error)||'Não foi possível entrar.'}finally{button.disabled=false}});
$('#logout').onclick=async()=>{unsubscribeOrders?.();sessionStorage.removeItem(K.session);try{await window.MingosSync.waitFirebase().then(f=>f.signOut())}finally{location.reload()}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab],.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#'+b.dataset.tab).classList.add('on')});
async function updateStatus(id,status){try{await window.MingosSync.updateStatus(id,status);audit('order_status_changed',{orderId:id,status});toast('Pedido atualizado em todos os dispositivos')}catch(error){console.error(error);toast('Não foi possível atualizar o pedido')}}
function urgency(o){const min=(Date.now()-new Date(o.createdAt).getTime())/60000;if(o.status==='completed')return ['',false];if(min>45)return ['urgency-late',true];if(min>30)return ['urgency-warning',false];if(min<=15)return ['urgency-ok',false];return ['',false]}
function renderOrders(){const today=new Date().toDateString(),todays=orders.filter(o=>new Date(o.createdAt).toDateString()===today),visible=orders.filter(o=>`${o.code} ${o.customer?.name||''} ${o.customer?.phone||''}`.toLowerCase().includes(orderQuery));
 const revenue=todays.filter(o=>!['rejected','cancelled'].includes(o.status)).reduce((s,o)=>s+(+o.total||0),0),delivery=todays.filter(o=>o.deliveryMode==='delivery').length,pickup=todays.filter(o=>o.deliveryMode==='pickup').length;$('#m-orders').textContent=todays.length;$('#m-revenue').textContent=money(revenue);$('#m-ticket').textContent=money(todays.length?revenue/todays.length:0);$('#m-delivery').textContent=`${delivery} / ${pickup}`;$('#m-active').textContent=todays.filter(o=>!['completed','rejected','cancelled'].includes(o.status)).length;$('#m-done').textContent=todays.filter(o=>o.status==='completed').length;
 const goal=+read(K.goal,1000)||1000,pct=Math.min(100,revenue/goal*100);$('#goal-label').textContent=`${money(revenue)} de ${money(goal)}`;$('#goal-progress').style.width=pct+'%';$('#goal-message').textContent=pct>=100?'Meta batida! Excelente trabalho.':`Faltam ${money(Math.max(0,goal-revenue))} para a meta de hoje.`;
 $('#board').innerHTML=statuses.map(([id,label])=>{const list=visible.filter(o=>(o.status||'pending_acceptance')===id);return `<section class="column" data-drop-status="${id}"><h2>${label}<b>${list.length}</b></h2><div class="cards">${list.map(o=>{const[u,late]=urgency(o);return `<article class="order ${u} ${o.unreadAdmin?'has-message':''}" draggable="${id!=='pending_acceptance'}" data-drag-id="${o.id}"><button class="order-main" data-order="${o.id}"><small>#${esc(o.code)} ${late?'<em class="late-alert">Atrasado!</em>':''}${o.unreadAdmin?'<em class="message-alert">💬 Nova mensagem</em>':''}</small><h3>${esc(o.customer?.name||'Cliente')}</h3><p>${(o.items||[]).map(i=>`${i.quantity}x ${esc(i.name)}`).join(', ')}</p><footer><b>${money(o.total)}</b><time>${new Date(o.createdAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></footer></button>${id==='pending_acceptance'?`<div class="accept-actions"><button data-accept="${o.id}">Aceitar pedido</button><button data-reject="${o.id}">Recusar</button></div>`:''}${id==='delivering'?`<button class="dispatch-btn" data-motoboy="${o.id}" title="Chamar motoboy">🏍️ Chamar motoboy</button>`:''}${id!=='pending_acceptance'?`<select aria-label="Alterar status" data-status="${o.id}">${statuses.map(([v,n])=>`<option value="${v}" ${v===id?'selected':''}>${n}</option>`).join('')}</select>`:''}</article>`}).join('')||'<p class="empty-column">Arraste pedidos para cá</p>'}</div></section>`}).join('');bindDragDrop();renderChart(todays)}
function renderChart(list){const hours={};list.forEach(o=>{const h=Number(new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',hour12:false}).format(new Date(o.createdAt)))%24;hours[h]=(hours[h]||0)+1});const labels=Object.keys(hours).sort((a,b)=>a-b).map(h=>`${h}h`),data=Object.keys(hours).sort((a,b)=>a-b).map(h=>hours[h]);if(!window.Chart)return;if(peakChart)peakChart.destroy();peakChart=new Chart($('#peak-chart'),{type:'bar',data:{labels:labels.length?labels:['Sem pedidos'],datasets:[{label:'Pedidos',data:data.length?data:[0],backgroundColor:'#6c2bd9',borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}},x:{grid:{display:false}}}}})}
function bindDragDrop(){document.querySelectorAll('[data-drag-id]').forEach(card=>{card.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',card.dataset.dragId);card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'));let start=null;card.addEventListener('touchstart',e=>{const t=e.touches[0];start={x:t.clientX,y:t.clientY,id:card.dataset.dragId}},{passive:true});card.addEventListener('touchend',e=>{if(!start)return;const t=e.changedTouches[0],col=document.elementFromPoint(t.clientX,t.clientY)?.closest('[data-drop-status]');if(col&&Math.hypot(t.clientX-start.x,t.clientY-start.y)>35)updateStatus(start.id,col.dataset.dropStatus);start=null},{passive:true})});document.querySelectorAll('[data-drop-status]').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drop-target')});col.addEventListener('dragleave',()=>col.classList.remove('drop-target'));col.addEventListener('drop',e=>{e.preventDefault();col.classList.remove('drop-target');updateStatus(e.dataTransfer.getData('text/plain'),col.dataset.dropStatus)})})}
function renderProducts(){const visible=products.filter(p=>`${p.name} ${p.desc} ${p.cat}`.toLowerCase().includes(productQuery));$('#product-count').textContent=`${visible.length} produto${visible.length===1?'':'s'}`;$('#product-list').innerHTML=visible.map(p=>`<article class="product-row ${p.available===false?'is-unavailable':''}"><img src="${esc(p.img)}" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><small>${p.available===false?'● Esgotado':'● Disponível'}</small></div><b>${money(p.price)}</b><span>${esc(p.cat)}</span><div class="actions"><button data-toggle-product="${p.id}">${p.available===false?'Ativar':'Pausar'}</button><button data-edit="${p.id}">Editar</button><button class="delete" data-delete="${p.id}">Excluir</button></div></article>`).join('')||'<p style="padding:30px">Nenhum produto encontrado.</p>'}
function renderContacts(){const visible=contacts.filter(contact=>`${contact.name} ${contact.phone}`.toLowerCase().includes(contactQuery));$('#contact-count').textContent=`${visible.length} contato${visible.length===1?'':'s'}`;$('#contact-list').innerHTML=visible.map(contact=>`<article class="contact-card"><span>${esc(contact.name).slice(0,1).toUpperCase()}</span><div><h3>${esc(contact.name)}</h3><p>${esc(contact.phone)}</p></div><small><b>Participante do Clube</b>${new Date(contact.createdAt).toLocaleDateString('pt-BR')}</small><em>${contact.consent?'Consentimento registrado':'Sem consentimento'}</em></article>`).join('')||'<div class="empty-history"><span>♡</span><h3>Nenhum contato ainda</h3><p>As inscrições do Clube Mingos aparecerão aqui.</p></div>'}
function renderHistory(){$('#history-list').innerHTML=history.map(h=>`<article class="history-card"><div><small>${new Date(h.closedAt).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</small><h3>${money(h.revenue)}</h3></div><p><b>${h.completedOrders}</b> pedidos finalizados</p><p>Campeão: <b>${esc(h.topItem||'—')}</b></p></article>`).join('')||'<div class="empty-history"><span>🔐</span><h3>O cofre está vazio</h3><p>Os fechamentos confirmados aparecerão aqui.</p></div>'}
function flashDeal(){const f=read(K.flash,null);return f&&f.expiresAt>Date.now()?f:null}function renderFlash(){clearInterval(flashTimer);const f=flashDeal();if(!f){$('#flash-status').innerHTML='<b>Nenhuma promoção ativa</b><span>Ative uma campanha de 30 minutos quando desejar.</span>';return}const tick=()=>{const left=Math.max(0,f.expiresAt-Date.now()),m=String(Math.floor(left/60000)).padStart(2,'0'),s=String(Math.floor(left/1000)%60).padStart(2,'0');$('#flash-status').innerHTML=`<b>⚡ ${esc(f.title)}</b><span>Termina em ${m}:${s}</span>`;if(!left){localStorage.removeItem(K.flash);clearInterval(flashTimer);renderFlash()}};tick();flashTimer=setInterval(tick,1000)}
function renderOperation(){const op={...defaultOperation,...read(K.operation,{})};$('#store-accepting').checked=op.accepting!==false;$('#delivery-enabled').checked=op.deliveryEnabled!==false;$('#pickup-enabled').checked=op.pickupEnabled!==false;$('#store-open').value=op.openHour;$('#store-close').value=op.closeHour;$('#kitchen-load').value=op.kitchenLoad||'normal';$('#delivery-minutes').value=op.deliveryMinutes;$('#pickup-minutes').value=op.pickupMinutes;$('#minimum-order').value=op.minimumOrder;$('#payment-pix').checked=op.payments?.pix!==false;$('#payment-card').checked=op.payments?.card!==false;$('#payment-cash').checked=op.payments?.cash!==false;$('#change-mode').value=op.changeMode||'normal';$('#neighborhood-rates').value=(op.neighborhoods||[]).map(item=>`${item.name} = ${String(item.fee).replace('.',',')}`).join('\n')}
function renderAll(){renderOrders();renderProducts();renderHistory();renderFlash();renderOperation();$('#daily-goal').value=read(K.goal,1000)}function sync(){orders=read(K.orders);products=read(K.products);history=read(K.history);renderAll()}function successSound(){try{const c=new(window.AudioContext||window.webkitAudioContext)(),n=c.currentTime;[660,880,1100].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,n+i*.08);g.gain.exponentialRampToValueAtTime(.001,n+i*.08+.22);o.connect(g).connect(c.destination);o.start(n+i*.08);o.stop(n+i*.08+.24)})}catch{}}window.addEventListener('storage',event=>{if(event.key===K.orders){const next=read(K.orders),completed=next.find(n=>n.status==='completed'&&orders.some(o=>o.id===n.id&&o.status!=='completed'));if(completed){successSound();toast(`Pedido #${completed.code} confirmado pelo cliente`)}orders=next;renderAll()}else sync()});setInterval(()=>{if(!document.hidden)renderOrders()},60000);
function summary(){const done=orders.filter(o=>o.status==='completed'),count={};done.forEach(o=>(o.items||[]).forEach(i=>count[i.name]=(count[i.name]||0)+(+i.quantity||1)));const top=Object.entries(count).sort((a,b)=>b[1]-a[1])[0];return{revenue:done.reduce((s,o)=>s+(+o.total||0),0),completedOrders:done.length,totalOrders:orders.length,topItem:top?`${top[0]} (${top[1]}x)`:'Nenhum item'}}
function summaryText(s){return `📊 Fechamento Mingos — ${new Date().toLocaleDateString('pt-BR')}\n💰 Total faturado: ${money(s.revenue)}\n✅ Pedidos finalizados: ${s.completedOrders}\n🏆 Item mais vendido: ${s.topItem}`}
function openClose(){const s=summary();closeModal._summary=s;$('#close-day-summary').innerHTML=`<div><span>Total faturado</span><b>${money(s.revenue)}</b></div><div><span>Pedidos finalizados</span><b>${s.completedOrders}</b></div><div><span>Item mais vendido</span><b>${esc(s.topItem)}</b></div>${s.totalOrders-s.completedOrders>0?`<p class="close-warning">Atenção: ${s.totalOrders-s.completedOrders} pedido(s) ainda não finalizado(s).</p>`:''}`;closeModal.hidden=false}
async function copySummary(){const text=summaryText(closeModal._summary||summary());try{await navigator.clipboard.writeText(text)}catch{const x=document.createElement('textarea');x.value=text;document.body.append(x);x.select();document.execCommand('copy');x.remove()}toast('Resumo copiado para a área de transferência')}
async function confirmClose(){const active=orders.filter(order=>!['completed','rejected','cancelled','expired'].includes(order.status));if(active.length)return toast(`Finalize ou cancele ${active.length} pedido(s) antes de encerrar.`);const s=closeModal._summary||summary(),record={id:`cash-${Date.now()}`,closedAt:new Date().toISOString(),...s,ordersSnapshot:orders};try{const firebase=await window.MingosSync.waitFirebase();await firebase.saveDocument('cashHistory',record.id,record);await audit('cash_closed',{revenue:s.revenue,orders:s.completedOrders});await firebase.clearOrders();closeModal.hidden=true;toast('Expediente encerrado e salvo no cofre')}catch(error){console.error(error);toast('Não foi possível encerrar o expediente')}}
function motoboy(o){const paid=+String(o.payment?.changeFor||0).replace(',','.'),change=paid?Math.max(0,paid-(+o.total||0)):0,a=o.address||{};const msg=`🏍️ ENTREGA MINGOS\nCliente: ${o.customer?.name||''}\nTelefone: ${o.customer?.phone||''}\nEndereço: ${a.street||''}, ${a.number||''} — ${a.neighborhood||''}, ${a.city||''}\nReferência: ${a.reference||o.notes||'Não informada'}\nTroco: ${change?money(change):'Não precisa'}`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,'_blank')}
async function showOrder(o){const method={cash:'Dinheiro',pix:'Pix na entrega',card:'Cartão na entrega'}[o.payment?.method]||'Na entrega',paid=+String(o.payment?.changeFor||0).replace(',','.'),change=paid?Math.max(0,paid-o.total):null,a=o.address||{};$('#order-detail').innerHTML=`<div><span class="badge">${statuses.find(s=>s[0]===o.status)?.[1]||o.status}</span><h2>#${esc(o.code)}</h2></div><p><b>Cliente:</b> ${esc(o.customer?.name)} • ${esc(o.customer?.phone)}</p><p><b>Destino:</b> ${o.deliveryMode==='pickup'?'Retirada no balcão':`${esc(a.street)}, ${esc(a.number)} — ${esc(a.neighborhood)}, ${esc(a.city)}`}</p><div>${(o.items||[]).map(i=>`<div class="detail-line"><span>${i.quantity}x ${esc(i.name)}</span><b>${money(i.unitPrice*i.quantity)}</b></div>`).join('')}</div><p><b>Pagamento:</b> ${method}${change!==null?` • Troco ${money(change)}`:''}</p><p><b>Observações:</b> ${esc(o.notes||'Nenhuma')}</p><div class="detail-total"><span>Total</span><b>${money(o.total)}</b></div><section class="admin-chat"><header><b>Conversa com o cliente</b><span>Pedido #${esc(o.code)}</span></header><div id="admin-chat-messages"><p>Carregando conversa…</p></div><form id="admin-chat-form" data-chat-order="${o.id}"><textarea maxlength="500" placeholder="Responder ao cliente…" required></textarea><button class="primary">Enviar</button></form></section>`;orderModal.hidden=false;try{window._adminChatStop?.();const firebase=await window.MingosSync.waitFirebase();window._adminChatStop=firebase.watchMessages(o.id,messages=>{const body=$('#admin-chat-messages');body.innerHTML=messages.length?messages.map(m=>`<article class="${m.senderRole==='admin'?'mine':''}"><b>${m.senderRole==='admin'?'Mingos':esc(m.senderName||'Cliente')}</b><p>${esc(m.text)}</p></article>`).join(''):'<p>Nenhuma mensagem ainda.</p>';body.scrollTop=body.scrollHeight});if(o.unreadAdmin)firebase.saveDocument('orders',o.id,{...o,unreadAdmin:false})}catch(error){console.error(error)}}
function showProduct(p=null){$('#product-title').textContent=p?'Editar produto':'Novo produto';$('#product-form').reset();$('#prod-id').value=p?.id||'';$('#prod-name').value=p?.name||'';$('#prod-price').value=p?.price||'';$('#prod-cat').value=p?.cat||'acai';$('#prod-desc').value=p?.desc||'';$('#prod-tag').value=p?.tag||'';$('#prod-available').checked=p?.available!==false;$('#prod-img').value=p?.img||'';$('#prod-options').value=optionsToText(p?.opts);$('#prod-from').value=p?.availableFrom||'';$('#prod-until').value=p?.availableUntil||'';productModal.hidden=false}
document.addEventListener('change',e=>{if(e.target.dataset.status)updateStatus(e.target.dataset.status,e.target.value)});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close!==undefined)document.querySelectorAll('.overlay').forEach(x=>x.hidden=true);if(b.dataset.order)showOrder(orders.find(o=>o.id===b.dataset.order));if(b.dataset.accept){$('#accept-order-id').value=b.dataset.accept;$('#accept-order-modal').hidden=false}if(b.dataset.reject){const reason=prompt('Por que este pedido não pode ser atendido?','Item indisponível');if(reason)updateStatus(b.dataset.reject,'rejected',{rejectionReason:reason})}if(b.id==='reject-from-accept'){const id=$('#accept-order-id').value,reason=prompt('Informe o motivo para o cliente:','Não conseguiremos atender este pedido agora.');if(reason){await updateStatus(id,'rejected',{rejectionReason:reason});$('#accept-order-modal').hidden=true}}if(b.dataset.motoboy)motoboy(orders.find(o=>o.id===b.dataset.motoboy));if(b.dataset.edit)showProduct(products.find(p=>p.id===b.dataset.edit));if(b.dataset.toggleProduct){const p=products.find(item=>item.id===b.dataset.toggleProduct);try{await window.MingosSync.waitFirebase().then(f=>f.saveDocument('products',p.id,{...p,available:p.available===false}));toast(p.available===false?'Produto ativado':'Produto pausado')}catch(error){toast('Não foi possível alterar a disponibilidade')}}if(b.dataset.delete&&confirm('Excluir este produto do cardápio?')){try{await window.MingosSync.waitFirebase().then(f=>f.removeDocument('products',b.dataset.delete));toast('Produto excluído')}catch(error){console.error(error);toast('Não foi possível excluir')}}if(b.id==='new-product')showProduct();if(b.id==='end-day')openClose();if(b.id==='copy-summary')copySummary();if(b.id==='confirm-close-day')confirmClose()});
$('#accept-order-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await updateStatus($('#accept-order-id').value,'accepted',{estimateLabel:$('#accept-estimate').value});$('#accept-order-modal').hidden=true;toast('Pedido aceito e cliente avisado')}finally{button.disabled=false}});
document.addEventListener('submit',async e=>{if(e.target.id!=='admin-chat-form')return;e.preventDefault();const input=e.target.querySelector('textarea'),button=e.submitter;button.disabled=true;try{await window.MingosSync.sendMessage(e.target.dataset.chatOrder,input.value,'admin');input.value='';toast('Mensagem enviada ao cliente')}catch(error){toast('Não foi possível enviar a mensagem')}finally{button.disabled=false}});
async function compressProductImage(file){if(!file?.type?.startsWith('image/'))throw new Error('Selecione uma imagem válida.');if(file.size>8*1024*1024)throw new Error('A imagem original deve ter no máximo 8 MB.');const bitmap=await createImageBitmap(file),size=720,scale=Math.min(1,size/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();const data=canvas.toDataURL('image/webp',.72);if(data.length>700000)throw new Error('A foto continuou muito pesada. Escolha uma imagem menor.');return data}
$('#product-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const old=$('#prod-id').value,id=old||`p-${crypto.randomUUID()}`,previous=products.find(p=>p.id===old)||{};try{const firebase=await window.MingosSync.waitFirebase(),file=$('#prod-file').files[0];let img=$('#prod-img').value.trim()||previous.img||'';if(file){button.textContent='Otimizando foto…';img=await compressProductImage(file)}if(!img)throw new Error('Adicione uma foto do produto.');const p={...previous,id,name:$('#prod-name').value.trim(),price:+$('#prod-price').value,cat:$('#prod-cat').value,desc:$('#prod-desc').value.trim(),img,tag:$('#prod-tag').value.trim()||'NOVIDADE',available:$('#prod-available').checked,availableFrom:$('#prod-from').value,availableUntil:$('#prod-until').value,opts:parseOptions($('#prod-options').value)};await firebase.saveDocument('products',id,p);productModal.hidden=true;toast('Produto salvo e publicado')}catch(error){console.error(error);toast(error.message||'Não foi possível salvar')}finally{button.disabled=false;button.textContent='Salvar e publicar'}});
$('#order-search').addEventListener('input',e=>{orderQuery=e.target.value.trim().toLowerCase();renderOrders()});$('#product-search').addEventListener('input',e=>{productQuery=e.target.value.trim().toLowerCase();renderProducts()});
$('#contact-search').addEventListener('input',e=>{contactQuery=e.target.value.trim().toLowerCase();renderContacts()});
$('#save-goal').onclick=async()=>{const v=+$('#daily-goal').value;if(v>0){await window.MingosSync.waitFirebase().then(f=>f.saveDocument('settings','goal',{value:v}));toast('Meta diária atualizada')}};
async function saveOperation(includeRates=false){const previous={...defaultOperation,...read(K.operation,{})},lines=$('#neighborhood-rates').value.split('\n').map(line=>line.trim()).filter(Boolean),neighborhoods=includeRates?lines.map(line=>{const[name,fee]=line.split('=');return{name:String(name||'').trim(),fee:Number(String(fee||'0').trim().replace(',','.'))}}).filter(item=>item.name&&item.fee>=0):previous.neighborhoods,operation={accepting:$('#store-accepting').checked,deliveryEnabled:$('#delivery-enabled').checked,pickupEnabled:$('#pickup-enabled').checked,kitchenLoad:$('#kitchen-load').value,openHour:$('#store-open').value,closeHour:$('#store-close').value,deliveryMinutes:$('#delivery-minutes').value.trim()||'30–45',pickupMinutes:$('#pickup-minutes').value.trim()||'15–25',minimumOrder:Math.max(0,+$('#minimum-order').value||0),payments:{pix:$('#payment-pix').checked,card:$('#payment-card').checked,cash:$('#payment-cash').checked},changeMode:$('#change-mode').value,neighborhoods};if(!operation.openHour||!operation.closeHour)return toast('Informe os horários da loja');if(!operation.deliveryEnabled&&!operation.pickupEnabled&&operation.accepting)return toast('Ative entrega ou retirada, ou pause a loja');if(!operation.payments.pix&&!operation.payments.card&&!operation.payments.cash&&operation.accepting)return toast('Ative pelo menos uma forma de pagamento');if(!neighborhoods.length)return toast('Cadastre pelo menos um bairro');await window.MingosSync.waitFirebase().then(f=>f.saveDocument('settings','operation',{value:operation}));write(K.operation,operation);toast('Configurações publicadas na loja')}
$('#save-operation').onclick=()=>saveOperation(false).catch(error=>{console.error(error);toast('Não foi possível publicar')});
$('#save-payments').onclick=()=>saveOperation(false).catch(error=>{console.error(error);toast('Não foi possível publicar os pagamentos')});
$('#save-neighborhoods').onclick=()=>saveOperation(true).catch(error=>{console.error(error);toast('Revise os bairros e taxas')});
$('#save-ingredients').onclick=async()=>{const value=$('#paused-ingredients').value.split('\n').map(item=>item.trim()).filter(Boolean);await window.MingosSync.waitFirebase().then(firebase=>firebase.saveDocument('settings','ingredients',{value}));write(K.ingredients,value);toast('Ingredientes atualizados na loja')};
$('#save-contact').onclick=async()=>{const whatsappNumber=$('#store-whatsapp').value.replace(/\D/g,'');if(whatsappNumber.length<12)return toast('Informe país, DDD e número.');await window.MingosSync.waitFirebase().then(firebase=>firebase.saveDocument('settings','contact',{value:{whatsappNumber}}));toast('WhatsApp oficial atualizado')};
$('#save-coupon').onclick=async()=>{const code=$('#coupon-code').value.trim().toUpperCase(),percent=Math.max(1,Math.min(70,Number($('#coupon-percent').value)||0)),minimum=Math.max(0,Number($('#coupon-minimum').value)||0);if(code.length<3)return toast('Informe um código com pelo menos 3 caracteres.');await window.MingosSync.waitFirebase().then(firebase=>firebase.saveDocument('coupons',code,{code,percent,minimum,active:true,updatedAt:new Date().toISOString()}));toast(`Cupom ${code} publicado`)};
$('#save-delivery-rule').onclick=async()=>{const freeDeliveryMinimum=Math.max(0,Number($('#free-delivery-minimum').value)||0);await window.MingosSync.waitFirebase().then(firebase=>firebase.saveDocument('settings','deliveryRules',{value:{freeDeliveryMinimum}}));toast('Meta de frete grátis publicada')};
$('#activate-flash').onclick=async()=>{const type=$('#flash-benefit').value,title=type==='delivery'?'Choveu! Entrega grátis':'Mini pastel de brinde',message=type==='delivery'?'Entrega grátis nos próximos 30 minutos!':'Ganhe um mini pastel nos próximos 30 minutos!';await window.MingosSync.waitFirebase().then(f=>f.saveDocument('settings','flash',{value:{type,title,message,expiresAt:Date.now()+1800000,active:true}}));toast('Promoção publicada para os clientes')};
$('#export-orders').onclick=()=>{const blob=new Blob([JSON.stringify(orders,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`pedidos-mingos-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href)};
$('#export-contacts').onclick=()=>{const rows=[['Nome','WhatsApp','Consentimento','Cadastro'],...contacts.filter(contact=>contact.consent).map(contact=>[contact.name,contact.phone,'Sim',new Date(contact.createdAt).toLocaleDateString('pt-BR')])],csv=rows.map(row=>row.map(value=>`"${String(value).replace(/"/g,'""')}"`).join(';')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`contatos-clube-mingos-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)};
function stopAdminChat(){window._adminChatStop?.();window._adminChatStop=null}
document.querySelectorAll('.overlay').forEach(x=>x.addEventListener('click',e=>{if(e.target===x){x.hidden=true;if(x===orderModal)stopAdminChat()}}));
orderModal.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',stopAdminChat));
window.MingosSync.waitFirebase().then(firebase=>firebase.watchCollection('settings',items=>{const setting=items.find(item=>item.id==='ingredients'),contact=items.find(item=>item.id==='contact'),delivery=items.find(item=>item.id==='deliveryRules');if(setting){write(K.ingredients,setting.value||[]);$('#paused-ingredients').value=(setting.value||[]).join('\n')}if(contact)$('#store-whatsapp').value=contact.value?.whatsappNumber||'';if(delivery)$('#free-delivery-minimum').value=Number(delivery.value?.freeDeliveryMinimum||65)})).catch(()=>{});
const unsafeMotoboy=motoboy;motoboy=o=>{if(!o)return toast('Este pedido não está mais disponível.');unsafeMotoboy(o)};
setInterval(()=>{if(!document.hidden&&orders.some(order=>order.status==='pending_acceptance'))successSound()},15000);
function printOrder(order){if(!order)return toast('Pedido indisponível.');const popup=window.open('','_blank','width=420,height=700');if(!popup)return toast('Permita a abertura da janela de impressão.');const address=order.deliveryMode==='pickup'?'RETIRADA NO BALCÃO':`${order.address?.street||''}, ${order.address?.number||''} - ${order.address?.neighborhood||''}`;popup.document.write(`<!doctype html><meta charset="utf-8"><title>Pedido ${esc(order.code)}</title><style>body{font:13px monospace;width:72mm;margin:4mm;color:#000}h1{text-align:center;font-size:20px}hr{border:0;border-top:1px dashed #000}.line{display:flex;justify-content:space-between;gap:8px;margin:7px 0}.center{text-align:center}@media print{button{display:none}}</style><h1>MINGOS</h1><p class="center">Pedido #${esc(order.code)}<br>${new Date(order.createdAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p><hr><p><b>${esc(order.customer?.name)}</b><br>${esc(order.customer?.phone)}<br>${esc(address)}</p><hr>${(order.items||[]).map(item=>`<div class="line"><span>${item.quantity}x ${esc(item.name)}${item.extras?.length?`<br><small>${item.extras.map(extra=>esc(extra.name)).join(', ')}</small>`:''}</span><b>${money(item.unitPrice*item.quantity)}</b></div>`).join('')}<hr><div class="line"><b>TOTAL</b><b>${money(order.total)}</b></div><p>Pagamento: ${esc(order.payment?.method||'')}</p><p>Observações: ${esc(order.notes||'Nenhuma')}</p><button onclick="print()">Imprimir</button>`);popup.document.close();popup.focus();setTimeout(()=>popup.print(),250)}
document.addEventListener('click',event=>{const open=event.target.closest('[data-order]');if(open)setTimeout(()=>{if(!$('#print-order')){$('#order-detail .detail-total')?.insertAdjacentHTML('afterend','<button id="print-order" class="primary">🧾 Imprimir para cozinha</button>')}},0);if(event.target.closest('#print-order'))printOrder(orders.find(order=>order.id===$('#admin-chat-form')?.dataset.chatOrder))});
})();
