(()=>{'use strict';
const K={products:'mingus_v3_products',orders:'mingus_v3_orders',last:'mingus_v3_last',session:'mingus_v3_admin',history:'mingos_cash_history',goal:'mingos_daily_goal',flash:'mingos_flash_deal'};
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=n=>(+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const $=s=>document.querySelector(s),statuses=[['received','Novo'],['preparing','Na chapa / montagem'],['delivering','Pronto para entrega'],['completed','Finalizados']];
let orders=[],products=[],history=[],orderQuery='',productQuery='',peakChart=null,flashTimer=null,unsubscribeOrders=null;
const login=$('#login'),app=$('#app'),orderModal=$('#order-modal'),productModal=$('#product-modal'),closeModal=$('#close-day-modal');
function toast(msg){const t=$('#admin-toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2800)}
async function enter(){login.hidden=true;app.hidden=false;sync();try{const firebase=await window.MingosSync.waitFirebase();unsubscribeOrders=await window.MingosSync.watchAdminOrders(next=>{orders=next;renderOrders()});firebase.watchCollection('products',async next=>{if(!next.length&&products.length){await Promise.all(products.map(product=>firebase.saveDocument('products',product.id,product)));return}products=next;write(K.products,products);renderProducts()});firebase.watchCollection('cashHistory',next=>{history=next.sort((a,b)=>new Date(b.closedAt)-new Date(a.closedAt));write(K.history,history);renderHistory()});firebase.watchCollection('settings',next=>{next.forEach(setting=>{if(setting.id==='goal')write(K.goal,setting.value);if(setting.id==='flash')write(K.flash,setting.value)});renderAll()})}catch(error){console.error(error);toast('Sem conexão com o Firebase')}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#login-error').textContent='Conectando…';try{await window.MingosSync.adminLogin($('#user').value.trim(),$('#pass').value);sessionStorage.setItem(K.session,'ok');$('#login-error').textContent='';await enter()}catch(error){console.error(error);$('#login-error').textContent='E-mail ou senha incorretos, ou conta sem permissão.'}finally{button.disabled=false}});
$('#logout').onclick=async()=>{unsubscribeOrders?.();sessionStorage.removeItem(K.session);try{await window.MingosSync.waitFirebase().then(f=>f.signOut())}finally{location.reload()}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab],.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#'+b.dataset.tab).classList.add('on')});
async function updateStatus(id,status){try{await window.MingosSync.updateStatus(id,status);toast('Pedido atualizado em todos os dispositivos')}catch(error){console.error(error);toast('Não foi possível atualizar o pedido')}}
function urgency(o){const min=(Date.now()-new Date(o.createdAt).getTime())/60000;if(o.status==='completed')return ['',false];if(min>45)return ['urgency-late',true];if(min>30)return ['urgency-warning',false];if(min<=15)return ['urgency-ok',false];return ['',false]}
function renderOrders(){const today=new Date().toDateString(),todays=orders.filter(o=>new Date(o.createdAt).toDateString()===today),visible=orders.filter(o=>`${o.code} ${o.customer?.name||''} ${o.customer?.phone||''}`.toLowerCase().includes(orderQuery));
 const revenue=todays.reduce((s,o)=>s+(+o.total||0),0);$('#m-orders').textContent=todays.length;$('#m-revenue').textContent=money(revenue);$('#m-active').textContent=todays.filter(o=>o.status!=='completed').length;$('#m-done').textContent=todays.filter(o=>o.status==='completed').length;
 const goal=+read(K.goal,1000)||1000,pct=Math.min(100,revenue/goal*100);$('#goal-label').textContent=`${money(revenue)} de ${money(goal)}`;$('#goal-progress').style.width=pct+'%';$('#goal-message').textContent=pct>=100?'Meta batida! Excelente trabalho.':`Faltam ${money(Math.max(0,goal-revenue))} para a meta de hoje.`;
 $('#board').innerHTML=statuses.map(([id,label])=>{const list=visible.filter(o=>(o.status||'received')===id);return `<section class="column" data-drop-status="${id}"><h2>${label}<b>${list.length}</b></h2><div class="cards">${list.map(o=>{const[u,late]=urgency(o);return `<article class="order ${u}" draggable="true" data-drag-id="${o.id}"><button class="order-main" data-order="${o.id}"><small>#${esc(o.code)} ${late?'<em class="late-alert">Atrasado!</em>':''}</small><h3>${esc(o.customer?.name||'Cliente')}</h3><p>${(o.items||[]).map(i=>`${i.quantity}x ${esc(i.name)}`).join(', ')}</p><footer><b>${money(o.total)}</b><time>${new Date(o.createdAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></footer></button>${id==='delivering'?`<button class="dispatch-btn" data-motoboy="${o.id}" title="Chamar motoboy">🏍️ Chamar motoboy</button>`:''}<select aria-label="Alterar status" data-status="${o.id}">${statuses.map(([v,n])=>`<option value="${v}" ${v===id?'selected':''}>${n}</option>`).join('')}</select></article>`}).join('')||'<p class="empty-column">Arraste pedidos para cá</p>'}</div></section>`}).join('');bindDragDrop();renderChart(todays)}
function renderChart(list){const hours={};list.forEach(o=>{const h=new Date(o.createdAt).getHours();hours[h]=(hours[h]||0)+1});const labels=Object.keys(hours).sort((a,b)=>a-b).map(h=>`${h}h`),data=Object.keys(hours).sort((a,b)=>a-b).map(h=>hours[h]);if(!window.Chart)return;if(peakChart)peakChart.destroy();peakChart=new Chart($('#peak-chart'),{type:'bar',data:{labels:labels.length?labels:['Sem pedidos'],datasets:[{label:'Pedidos',data:data.length?data:[0],backgroundColor:'#6c2bd9',borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}},x:{grid:{display:false}}}}})}
function bindDragDrop(){document.querySelectorAll('[data-drag-id]').forEach(card=>{card.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',card.dataset.dragId);card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'));let start=null;card.addEventListener('touchstart',e=>{const t=e.touches[0];start={x:t.clientX,y:t.clientY,id:card.dataset.dragId}},{passive:true});card.addEventListener('touchend',e=>{if(!start)return;const t=e.changedTouches[0],col=document.elementFromPoint(t.clientX,t.clientY)?.closest('[data-drop-status]');if(col&&Math.hypot(t.clientX-start.x,t.clientY-start.y)>35)updateStatus(start.id,col.dataset.dropStatus);start=null},{passive:true})});document.querySelectorAll('[data-drop-status]').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drop-target')});col.addEventListener('dragleave',()=>col.classList.remove('drop-target'));col.addEventListener('drop',e=>{e.preventDefault();col.classList.remove('drop-target');updateStatus(e.dataTransfer.getData('text/plain'),col.dataset.dropStatus)})})}
function renderProducts(){const visible=products.filter(p=>`${p.name} ${p.desc} ${p.cat}`.toLowerCase().includes(productQuery));$('#product-count').textContent=`${visible.length} produto${visible.length===1?'':'s'}`;$('#product-list').innerHTML=visible.map(p=>`<article class="product-row"><img src="${esc(p.img)}" alt=""><div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p></div><b>${money(p.price)}</b><span>${esc(p.cat)}</span><div class="actions"><button data-edit="${p.id}">Editar</button><button class="delete" data-delete="${p.id}">Excluir</button></div></article>`).join('')||'<p style="padding:30px">Nenhum produto encontrado.</p>'}
function renderHistory(){$('#history-list').innerHTML=history.map(h=>`<article class="history-card"><div><small>${new Date(h.closedAt).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</small><h3>${money(h.revenue)}</h3></div><p><b>${h.completedOrders}</b> pedidos finalizados</p><p>Campeão: <b>${esc(h.topItem||'—')}</b></p></article>`).join('')||'<div class="empty-history"><span>🔐</span><h3>O cofre está vazio</h3><p>Os fechamentos confirmados aparecerão aqui.</p></div>'}
function flashDeal(){const f=read(K.flash,null);return f&&f.expiresAt>Date.now()?f:null}function renderFlash(){clearInterval(flashTimer);const f=flashDeal();if(!f){$('#flash-status').innerHTML='<b>Nenhuma promoção ativa</b><span>Ative uma campanha de 30 minutos quando desejar.</span>';return}const tick=()=>{const left=Math.max(0,f.expiresAt-Date.now()),m=String(Math.floor(left/60000)).padStart(2,'0'),s=String(Math.floor(left/1000)%60).padStart(2,'0');$('#flash-status').innerHTML=`<b>⚡ ${esc(f.title)}</b><span>Termina em ${m}:${s}</span>`;if(!left){localStorage.removeItem(K.flash);clearInterval(flashTimer);renderFlash()}};tick();flashTimer=setInterval(tick,1000)}
function renderAll(){renderOrders();renderProducts();renderHistory();renderFlash();$('#daily-goal').value=read(K.goal,1000)}function sync(){orders=read(K.orders);products=read(K.products);history=read(K.history);renderAll()}function successSound(){try{const c=new(window.AudioContext||window.webkitAudioContext)(),n=c.currentTime;[660,880,1100].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,n+i*.08);g.gain.exponentialRampToValueAtTime(.001,n+i*.08+.22);o.connect(g).connect(c.destination);o.start(n+i*.08);o.stop(n+i*.08+.24)})}catch{}}window.addEventListener('storage',event=>{if(event.key===K.orders){const next=read(K.orders),completed=next.find(n=>n.status==='completed'&&orders.some(o=>o.id===n.id&&o.status!=='completed'));if(completed){successSound();toast(`Pedido #${completed.code} confirmado pelo cliente`)}orders=next;renderAll()}else sync()});setInterval(()=>{if(!document.hidden)renderOrders()},60000);
function summary(){const done=orders.filter(o=>o.status==='completed'),count={};done.forEach(o=>(o.items||[]).forEach(i=>count[i.name]=(count[i.name]||0)+(+i.quantity||1)));const top=Object.entries(count).sort((a,b)=>b[1]-a[1])[0];return{revenue:done.reduce((s,o)=>s+(+o.total||0),0),completedOrders:done.length,totalOrders:orders.length,topItem:top?`${top[0]} (${top[1]}x)`:'Nenhum item'}}
function summaryText(s){return `📊 Fechamento Mingos — ${new Date().toLocaleDateString('pt-BR')}\n💰 Total faturado: ${money(s.revenue)}\n✅ Pedidos finalizados: ${s.completedOrders}\n🏆 Item mais vendido: ${s.topItem}`}
function openClose(){const s=summary();closeModal._summary=s;$('#close-day-summary').innerHTML=`<div><span>Total faturado</span><b>${money(s.revenue)}</b></div><div><span>Pedidos finalizados</span><b>${s.completedOrders}</b></div><div><span>Item mais vendido</span><b>${esc(s.topItem)}</b></div>${s.totalOrders-s.completedOrders>0?`<p class="close-warning">Atenção: ${s.totalOrders-s.completedOrders} pedido(s) ainda não finalizado(s).</p>`:''}`;closeModal.hidden=false}
async function copySummary(){const text=summaryText(closeModal._summary||summary());try{await navigator.clipboard.writeText(text)}catch{const x=document.createElement('textarea');x.value=text;document.body.append(x);x.select();document.execCommand('copy');x.remove()}toast('Resumo copiado para a área de transferência')}
async function confirmClose(){const s=closeModal._summary||summary(),record={id:`cash-${Date.now()}`,closedAt:new Date().toISOString(),...s,ordersSnapshot:orders};try{const firebase=await window.MingosSync.waitFirebase();await firebase.saveDocument('cashHistory',record.id,record);await firebase.clearOrders();closeModal.hidden=true;toast('Expediente encerrado e salvo no cofre')}catch(error){console.error(error);toast('Não foi possível encerrar o expediente')}}
function motoboy(o){const paid=+String(o.payment?.changeFor||0).replace(',','.'),change=paid?Math.max(0,paid-(+o.total||0)):0,a=o.address||{};const msg=`🏍️ ENTREGA MINGOS\nCliente: ${o.customer?.name||''}\nTelefone: ${o.customer?.phone||''}\nEndereço: ${a.street||''}, ${a.number||''} — ${a.neighborhood||''}, ${a.city||''}\nReferência: ${a.reference||o.notes||'Não informada'}\nTroco: ${change?money(change):'Não precisa'}`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,'_blank')}
function showOrder(o){const method={cash:'Dinheiro',pix:'Pix na entrega',card:'Cartão na entrega'}[o.payment?.method]||'Na entrega',paid=+String(o.payment?.changeFor||0).replace(',','.'),change=paid?Math.max(0,paid-o.total):null,a=o.address||{};$('#order-detail').innerHTML=`<div><span class="badge">${statuses.find(s=>s[0]===o.status)?.[1]||'Novo'}</span><h2>#${esc(o.code)}</h2></div><p><b>Cliente:</b> ${esc(o.customer?.name)} • ${esc(o.customer?.phone)}</p><p><b>Destino:</b> ${o.deliveryMode==='pickup'?'Retirada no balcão':`${esc(a.street)}, ${esc(a.number)} — ${esc(a.neighborhood)}, ${esc(a.city)}`}</p><div>${(o.items||[]).map(i=>`<div class="detail-line"><span>${i.quantity}x ${esc(i.name)}</span><b>${money(i.unitPrice*i.quantity)}</b></div>`).join('')}</div><p><b>Pagamento:</b> ${method}${change!==null?` • Troco ${money(change)}`:''}</p><p><b>Observações:</b> ${esc(o.notes||'Nenhuma')}</p><div class="detail-total"><span>Total</span><b>${money(o.total)}</b></div>`;orderModal.hidden=false}
function showProduct(p=null){$('#product-title').textContent=p?'Editar produto':'Novo produto';$('#product-form').reset();$('#prod-id').value=p?.id||'';$('#prod-name').value=p?.name||'';$('#prod-price').value=p?.price||'';$('#prod-cat').value=p?.cat||'acai';$('#prod-desc').value=p?.desc||'';$('#prod-img').value=p?.img||'';productModal.hidden=false}
document.addEventListener('change',e=>{if(e.target.dataset.status)updateStatus(e.target.dataset.status,e.target.value)});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close!==undefined)document.querySelectorAll('.overlay').forEach(x=>x.hidden=true);if(b.dataset.order)showOrder(orders.find(o=>o.id===b.dataset.order));if(b.dataset.motoboy)motoboy(orders.find(o=>o.id===b.dataset.motoboy));if(b.dataset.edit)showProduct(products.find(p=>p.id===b.dataset.edit));if(b.dataset.delete&&confirm('Excluir este produto do cardápio?')){try{await window.MingosSync.waitFirebase().then(f=>f.removeDocument('products',b.dataset.delete));toast('Produto excluído')}catch(error){console.error(error);toast('Não foi possível excluir')}}if(b.id==='new-product')showProduct();if(b.id==='end-day')openClose();if(b.id==='copy-summary')copySummary();if(b.id==='confirm-close-day')confirmClose()});
$('#product-form').addEventListener('submit',async e=>{e.preventDefault();const old=$('#prod-id').value,id=old||`p-${Date.now()}`,previous=products.find(p=>p.id===old)||{};const p={...previous,id,name:$('#prod-name').value.trim(),price:+$('#prod-price').value,cat:$('#prod-cat').value,desc:$('#prod-desc').value.trim(),img:$('#prod-img').value.trim(),tag:previous.tag||'NOVIDADE',opts:previous.opts||[]};try{await window.MingosSync.waitFirebase().then(f=>f.saveDocument('products',id,p));productModal.hidden=true;toast('Produto salvo e publicado')}catch(error){console.error(error);toast('Não foi possível salvar')}});
$('#order-search').addEventListener('input',e=>{orderQuery=e.target.value.trim().toLowerCase();renderOrders()});$('#product-search').addEventListener('input',e=>{productQuery=e.target.value.trim().toLowerCase();renderProducts()});
$('#save-goal').onclick=async()=>{const v=+$('#daily-goal').value;if(v>0){await window.MingosSync.waitFirebase().then(f=>f.saveDocument('settings','goal',{value:v}));toast('Meta diária atualizada')}};
$('#activate-flash').onclick=async()=>{const type=$('#flash-benefit').value,title=type==='delivery'?'Choveu! Entrega grátis':'Mini pastel de brinde',message=type==='delivery'?'Entrega grátis nos próximos 30 minutos!':'Ganhe um mini pastel nos próximos 30 minutos!';await window.MingosSync.waitFirebase().then(f=>f.saveDocument('settings','flash',{value:{type,title,message,expiresAt:Date.now()+1800000,active:true}}));toast('Promoção publicada para os clientes')};
$('#export-orders').onclick=()=>{const blob=new Blob([JSON.stringify(orders,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`pedidos-mingos-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href)};
document.querySelectorAll('.overlay').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)x.hidden=true}));
})();
