(() => {
  'use strict';

  const KEYS = { products:'mingus_v3_products', orders:'mingus_v3_orders', cart:'mingus_v3_cart', last:'mingus_v3_last', ultimoPedido:'ultimoPedido', user:'mingos_user', muted:'mingos_muted', flash:'mingos_flash_deal' };
  const IMG = {
    pastel:'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=85',
    acai:'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=900&q=85',
    fruit:'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=900&q=85',
    sweet:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=85',
    drink:'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=85'
  };
  const acaiOptions=[{name:'Complementos',max:4,items:['Banana','Morango','Granola','Leite em pó','Paçoca','Coco ralado']},{name:'Cobertura',max:1,items:['Leite condensado|2','Chocolate|2','Sem cobertura']}];
  const pastelOptions=[{name:'Acréscimos',max:2,items:['Borda recheada de Catupiry|4','Dobro de Queijo|3']},{name:'Retiradas',max:3,items:['Sem Cebola','Sem Azeitona','Sem Milho']},{name:'Preparo',max:1,items:['Frito','Assado']}];
  const defaults=[
    {id:'a300',cat:'acai',name:'Açaí 300 ml',desc:'Açaí cremoso + até 4 adicionais à escolha.',price:16.9,img:IMG.acai,tag:'Leve',opts:acaiOptions},
    {id:'a500',cat:'acai',name:'Açaí 500 ml',desc:'A medida favorita + até 4 adicionais.',price:22.9,img:IMG.fruit,tag:'Mais pedido',opts:acaiOptions},
    {id:'a700',cat:'acai',name:'Açaí 700 ml',desc:'Generoso, gelado e montado do seu jeito.',price:29.9,img:IMG.acai,tag:'Tamanho fome',opts:acaiOptions},
    {id:'a1l',cat:'acai',name:'Barca 1 litro',desc:'Para compartilhar com complementos caprichados.',price:42.9,img:IMG.fruit,tag:'Para dividir',opts:acaiOptions},
    {id:'pcarne',cat:'pasteis',name:'Carne da casa',desc:'Carne temperada, cebola e cheiro-verde.',price:14.9,img:IMG.pastel,tag:'Clássico',opts:pastelOptions},
    {id:'pqueijo',cat:'pasteis',name:'Queijo puxa-puxa',desc:'Muçarela generosa e orégano.',price:13.9,img:IMG.pastel,tag:'Favorito',opts:pastelOptions},
    {id:'pfrango',cat:'pasteis',name:'Frango cremoso',desc:'Frango desfiado, milho e catupiry.',price:16.9,img:IMG.pastel,tag:'Cremoso',opts:pastelOptions},
    {id:'ppizza',cat:'pasteis',name:'Pizza de feira',desc:'Queijo, presunto, tomate e orégano.',price:15.9,img:IMG.pastel,tag:'Nostalgia',opts:pastelOptions},
    {id:'pdocel',cat:'pasteis',name:'Doce de leite',desc:'Crocante por fora, cremoso por dentro.',price:15.9,img:IMG.sweet,tag:'Doce',opts:pastelOptions},
    {id:'combo',cat:'combos',name:'Dupla Mingos',desc:'Dois pastéis clássicos + duas bebidas.',price:39.9,img:'assets/hero-mingus.png',tag:'Economize',opts:[]},
    {id:'combo2',cat:'combos',name:'Verão completo',desc:'Dois pastéis + açaí 500 ml.',price:49.9,img:'assets/hero-mingus.png',tag:'Combo',opts:[]},
    {id:'refri',cat:'bebidas',name:'Refrigerante lata',desc:'Cola, guaraná ou laranja bem gelado.',price:6.5,img:IMG.drink,tag:'Gelado',opts:[]}
  ];

  const $ = selector => document.querySelector(selector);
  const read = (key,fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
  const write = (key,value) => {localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent('mingos:sync',{detail:{key,value}}))};
  const cents=value=>Math.round((Number(value)||0)*100),fromCents=value=>Number((value/100).toFixed(2));
  const money = value => fromCents(cents(value)).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const esc = value => String(value ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const categories=[['all','✦','Todos'],['acai','●','Açaís'],['pasteis','◒','Pastéis'],['combos','⚡','Combos'],['bebidas','◫','Bebidas']];
  const contextualImages={a300:'assets/produtos/acai-300-v2.jpg',a500:'assets/produtos/acai-500-v2.jpg',a700:'assets/produtos/acai-700-v2.jpg',a1l:'assets/produtos/barca-acai-1l-v2.jpg',pcarne:'assets/produtos/pastel-carne-v2.jpg',pqueijo:'assets/produtos/pastel-queijo-v2.jpg',pfrango:'assets/produtos/pastel-frango-v2.jpg',ppizza:'assets/produtos/pastel-pizza-v2.jpg',pdocel:'assets/produtos/pastel-doce-leite-v2.jpg',combo:'assets/produtos/combo-dupla-v2.jpg',combo2:'assets/produtos/combo-verao-v2.jpg',refri:'assets/produtos/refrigerante-lata-v2.jpg'};
  let products=read(KEYS.products,null); if(!products?.length)products=defaults;products=products.map(product=>({...product,img:contextualImages[product.id]||product.img}));write(KEYS.products,products)
  let cart=read(KEYS.cart,[]).map(item=>({...item,unitPrice:fromCents(cents(item.unitPrice??item.unit??0)),quantity:Math.trunc(Number(item.quantity??item.qty??1)),extras:Array.isArray(item.extras)?item.extras:[]})).filter(item=>item.quantity>0&&item.unitPrice>=0),category='all',search='',mood='all',selected=null,quantity=1,selections=[],productNotes='',coupon=null,editingKey=null;
  let checkout={mode:'delivery',name:'',phone:'',neighborhood:'',street:'',number:'',city:'Tramandaí / RS',payment:'card',changeFor:'',notes:''};
  let wizard={step:1,size:null,base:null,extras:[],paidExtras:[]},skipUpsell=false,checkoutLocked=false;
  let muted=read(KEYS.muted,false),audioContext;

  const overlay=$('#overlay'),drawer=$('#cart-drawer'),productModal=$('#product-modal'),loginModal=$('#login-modal'),checkoutModal=$('#checkout-modal'),acaiWizard=$('#acai-wizard'),upsellModal=$('#upsell-modal'),cartChoiceModal=$('#cart-choice-modal');acaiWizard.querySelector('h2').textContent='Seu açaí em 3 passos';
  const layers=[drawer,productModal,loginModal,checkoutModal,acaiWizard,upsellModal,cartChoiceModal];
  const subtotal=()=>fromCents(cart.reduce((sum,item)=>sum+cents(item.unitPrice)*Math.max(1,Math.trunc(item.quantity)),0));
  const discount=()=>fromCents(coupon?Math.round(cents(subtotal())*.1):0);
  const activeFlash=()=>{const f=read(KEYS.flash,null);return f&&f.expiresAt>Date.now()?f:null};
  const deliveryFee=()=>activeFlash()?.type==='delivery'||subtotal()>=65?0:7.9;
  const total=()=>fromCents(Math.max(0,cents(subtotal())-cents(discount())+cents(deliveryFee())));
  const extrasTotal=()=>fromCents(selections.reduce((sum,item)=>sum+cents(item.price),0));

  function toast(message,type='success'){const container=$('#toast-container'),item=document.createElement('div');item.className='toast-premium rounded-2xl border border-white/60 bg-white/90 p-4 shadow-deep backdrop-blur-xl';item.innerHTML=`<div class="flex items-center gap-3"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-xl ${type==='error'?'bg-red-50 text-red-500':'bg-teal/10 text-teal'}">${type==='error'?'!':'✓'}</span><p class="text-sm font-semibold text-ink">${esc(message)}</p></div><i class="toast-bar"></i>`;container.appendChild(item);setTimeout(()=>{item.classList.add('out');setTimeout(()=>item.remove(),260)},3000)}
  function playSound(kind){if(muted)return;audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();const now=audioContext.currentTime;if(kind==='croc'){const buffer=audioContext.createBuffer(1,audioContext.sampleRate*.09,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;filter.type='highpass';filter.frequency.value=1800;gain.gain.setValueAtTime(.11,now);gain.gain.exponentialRampToValueAtTime(.001,now+.1);source.connect(filter).connect(gain).connect(audioContext.destination);source.start()}else{[760,1040].forEach((frequency,index)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.06,now+index*.05);gain.gain.exponentialRampToValueAtTime(.001,now+.23+index*.05);oscillator.connect(gain).connect(audioContext.destination);oscillator.start(now+index*.05);oscillator.stop(now+.28)})}}
  function celebrate(){if(typeof confetti!=='function')return;const colors=['#4B176D','#D99A21','#12AEB4','#FFFFFF'],end=Date.now()+1100;(function frame(){confetti({particleCount:5,angle:60,spread:60,origin:{x:0},colors,scalar:.9});confetti({particleCount:5,angle:120,spread:60,origin:{x:1},colors,scalar:.9});if(Date.now()<end)requestAnimationFrame(frame)})()}
  function setupParallax(){const media=$('#hero-media');if(!media||matchMedia('(prefers-reduced-motion: reduce)').matches)return;window.addEventListener('scroll',()=>{const rect=media.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight)media.style.transform=`translateY(${scrollY*.035}px)`},{passive:true})}
  function setupCarousel(){const track=$('#hero-carousel'),dots=$('#hero-dots');if(!track||!dots)return;const slides=[...track.children];let index=0,timer;dots.innerHTML=slides.map((_,i)=>`<button class="hero-dot ${i===0?'on':''}" data-hero-dot="${i}" aria-label="Destaque ${i+1}"></button>`).join('');const update=i=>{index=(i+slides.length)%slides.length;track.scrollTo({left:index*track.clientWidth,behavior:'smooth'});dots.querySelectorAll('button').forEach((dot,n)=>dot.classList.toggle('on',n===index))};const restart=()=>{clearInterval(timer);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)timer=setInterval(()=>update(index+1),5000)};dots.addEventListener('click',event=>{const dot=event.target.closest('[data-hero-dot]');if(dot){update(Number(dot.dataset.heroDot));restart()}});let raf;track.addEventListener('scroll',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{index=Math.round(track.scrollLeft/track.clientWidth);dots.querySelectorAll('button').forEach((dot,n)=>dot.classList.toggle('on',n===index))})},{passive:true});track.addEventListener('pointerdown',()=>clearInterval(timer));track.addEventListener('pointerup',restart);restart()}
  function openLayer(layer){overlay.classList.remove('hidden');layer.classList.remove('hidden');if(layer===drawer)requestAnimationFrame(()=>drawer.classList.remove('translate-x-full'));layer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
  function closeLayers(){drawer.classList.add('translate-x-full');setTimeout(()=>{layers.forEach(x=>{x.classList.add('hidden');x.setAttribute('aria-hidden','true')});overlay.classList.add('hidden')},drawer.classList.contains('hidden')?0:260);document.body.style.overflow=''}

  function renderCategories(){
    $('#categories').innerHTML=categories.map(([id,icon,label])=>`<button data-category="${id}" class="shrink-0 rounded-2xl border px-4 py-3 text-sm font-semibold transition ${category===id?'border-acai bg-acai text-white shadow-lg shadow-acai/15':'border-black/5 bg-white text-slate-600 hover:border-acai/20 hover:text-acai'}"><span class="mr-2">${icon}</span>${label}</button>`).join('');
  }
  function productCard(p,index){const simple=p.cat==='bebidas'&&!(p.opts||[]).length,social=p.id==='a500'?'🔥 Mais pedido':p.id==='pqueijo'?'⭐ 4.9':p.tag||p.cat,featured=['a500','pqueijo','combo2'].includes(p.id);return`<article data-product-card="${p.id}" ${featured?'data-tilt':''} class="product-card ${featured?'tilt-card':''} group overflow-hidden rounded-[1.25rem] border border-black/5 bg-white p-2 shadow-soft sm:rounded-[1.5rem] sm:p-3" style="animation-delay:${Math.min(index,7)*45}ms"><i class="tilt-shine"></i><div class="relative overflow-visible rounded-[1rem] bg-gradient-to-br from-sand to-white sm:rounded-[1.15rem]"><div class="overflow-hidden rounded-[1rem]"><img src="${esc(p.img)}" alt="${esc(p.name)}" class="bleed-image aspect-square w-full object-cover" loading="lazy"></div><span class="absolute left-2 top-2 rounded-full bg-white/90 px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-acai shadow-sm backdrop-blur sm:left-3 sm:top-3 sm:text-[10px]">${esc(social)}</span>${simple?`<button data-quick-add="${p.id}" class="ripple direct-badge absolute bottom-2 right-2 grid h-11 w-11 place-items-center rounded-full text-2xl shadow-lg transition hover:scale-110 sm:bottom-3 sm:right-3" aria-label="Adicionar ${esc(p.name)} rapidamente">+</button>`:`<button data-product="${p.id}" class="ripple complex-badge absolute bottom-2 right-2 min-h-11 rounded-full px-3 text-[10px] font-bold uppercase tracking-wide shadow-lg transition hover:scale-105 sm:bottom-3 sm:right-3">Montar</button>`}</div><div class="px-1 pb-2 pt-3 sm:px-1.5"><h3 class="line-clamp-2 font-display text-sm font-bold leading-tight sm:text-lg">${esc(p.name)}</h3><p class="mt-1 line-clamp-2 min-h-8 text-[10px] leading-4 text-slate-500 sm:min-h-10 sm:text-xs sm:leading-5">${esc(p.desc)}</p><strong class="mt-2 block font-display text-base text-gold sm:text-xl">${money(p.price)}</strong></div></article>`}
  function renderSkeleton(){const blocks=Array.from({length:8},()=>'<article class="rounded-[1.25rem] bg-white p-2 shadow-sm"><div class="skeleton aspect-square rounded-[1rem]"></div><div class="p-2"><div class="skeleton mt-1 h-4 w-3/4 rounded"></div><div class="skeleton mt-3 h-3 w-full rounded"></div><div class="skeleton mt-2 h-5 w-1/3 rounded"></div></div></article>').join('');$('#product-sections').innerHTML=`<div class="grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3 xl:grid-cols-4">${blocks}</div>`}
  function renderProducts(){
    const matchesMood=p=>mood==='all'||(mood==='share'&&(p.cat==='combos'||p.id==='a1l'))||(mood==='refresh'&&(p.cat==='acai'||p.cat==='bebidas'))||(mood==='hungry'&&(p.cat==='pasteis'||p.cat==='combos'||['a700','a1l'].includes(p.id)));const visible=products.filter(p=>`${p.name} ${p.desc}`.toLowerCase().includes(search.toLowerCase())&&matchesMood(p));
    $('#results').textContent=`${visible.length} ${visible.length===1?'opção':'opções'} preparada${visible.length===1?'':'s'} para você`;$('#empty').classList.toggle('hidden',!!visible.length);
    const groups=[['acai','Açaís','Cremosos, gelados e montados por você.'],['pasteis','Pastéis artesanais','Massa crocante e recheio de verdade.'],['combos','Combos Mingos','Para dividir ou matar uma fome maior.'],['bebidas','Bebidas','Para acompanhar bem geladinha.']];
    $('#product-sections').innerHTML=groups.map(([id,title,copy])=>{const list=visible.filter(p=>p.cat===id);if(!list.length)return'';return`<section id="category-${id}" data-product-section="${id}" class="scroll-mt-40"><div class="mb-5 flex items-end justify-between"><div><h3 class="font-display text-2xl font-bold tracking-tight">${title}</h3><p class="mt-1 text-sm text-slate-500">${copy}</p></div><span class="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-400">${list.length}</span></div><div class="grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3 xl:grid-cols-4">${list.map(productCard).join('')}</div></section>`}).join('');initScrollSpy();setupTilt();
  }
  function saveCart(){write(KEYS.cart,cart);renderCart()}
  function rewardCart(){const icon=$('#mobile-cart');icon.classList.remove('cart-bounce');void icon.offsetWidth;icon.classList.add('cart-bounce');setTimeout(()=>icon.classList.remove('cart-bounce'),550)}
  function renderCart(){
    const count=cart.reduce((sum,item)=>sum+item.quantity,0);$('#cart-count').textContent=count;$('#mobile-cart-badge').textContent=count;$('#mobile-cart-count').textContent=count?`${count} ${count===1?'item':'itens'}`:'Sacola vazia';$('#mobile-cart-total').textContent=count?money(total()):'Ver carrinho';
    if(!count){$('#cart-items').innerHTML='<div class="grid h-full place-content-center py-20 text-center"><div class="mx-auto grid h-20 w-20 place-items-center rounded-full bg-sand text-3xl">◇</div><h3 class="mt-5 font-display text-xl font-bold">Sua sacola está vazia</h3><p class="mt-2 text-sm text-slate-500">Escolha algo gostoso para começar.</p><button data-close class="mt-6 font-bold text-acai">Explorar cardápio</button></div>';$('#cart-footer').innerHTML='';return}
    const goal=subtotal()<65?65:85,remaining=Math.max(0,goal-subtotal()),progress=Math.min(100,subtotal()/goal*100),reward=goal===65?'Frete Grátis':'Mini Churros';const progressHtml=`<div class="mb-4 rounded-2xl bg-gradient-to-r from-acai/5 to-teal/5 p-4"><div class="flex items-center justify-between gap-3 text-xs"><b class="text-acai">${remaining?`Faltam ${money(remaining)} para ${reward}`:`Você ganhou ${reward}!`}</b><span>${Math.round(progress)}%</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-white"><i class="block h-full rounded-full bg-gradient-to-r from-acai to-teal transition-all" style="width:${progress}%"></i></div></div>`;$('#cart-items').innerHTML=progressHtml+cart.map(item=>`<div class="swipe-row" data-swipe-row="${item.key}"><button data-remove-cart="${item.key}" class="swipe-delete" aria-label="Excluir ${esc(item.name)}">⌫</button><article data-edit-cart="${item.key}" class="swipe-content flex cursor-pointer gap-3 border-b border-black/5 px-1 py-4"><img src="${esc(item.img)}" alt="" class="h-20 w-20 rounded-2xl object-cover"><div class="min-w-0 flex-1"><h3 class="truncate font-display text-sm font-bold">${esc(item.name)}</h3><p class="mt-1 line-clamp-1 text-[10px] text-slate-400">${esc((item.extras||[]).map(x=>x.name).join(', ')||'Toque para editar')}</p><div class="mt-3 inline-flex items-center gap-2 rounded-xl bg-sand p-1"><button data-cart="${item.key}" data-qty="-1" class="grid h-11 w-11 place-items-center rounded-lg bg-white font-bold">−</button><b class="min-w-5 text-center text-xs">${item.quantity}</b><button data-cart="${item.key}" data-qty="1" class="grid h-11 w-11 place-items-center rounded-lg bg-white font-bold">+</button></div></div><strong class="text-sm text-acai">${money(item.unitPrice*item.quantity)}</strong></article></div>`).join('');initSwipe();
    $('#cart-footer').innerHTML=`<div class="mb-4 flex gap-2"><input id="coupon-input" class="min-w-0 flex-1 rounded-xl border border-black/10 bg-sand px-4 py-3 text-sm outline-none focus:border-acai" placeholder="Cupom de desconto" value="${coupon?'MINGOS10':''}"><button id="apply-coupon" class="min-h-11 rounded-xl bg-ink px-4 text-xs font-bold text-white">Aplicar</button></div>${coupon?'<p class="mb-3 text-xs font-semibold text-teal">✓ MINGOS10 aplicado: 10% de desconto</p>':''}<div class="space-y-2 text-sm text-slate-500"><p class="flex justify-between"><span>Subtotal</span><b class="text-ink">${money(subtotal())}</b></p>${coupon?`<p class="flex justify-between text-teal"><span>Desconto</span><b>− ${money(discount())}</b></p>`:''}<p class="flex justify-between"><span>Taxa de entrega</span><b class="text-ink">${deliveryFee()?money(deliveryFee()):'Grátis'}</b></p><p class="flex justify-between border-t border-black/5 pt-3 font-display text-lg font-bold text-ink"><span>Total</span><b>${money(total())}</b></p></div><div class="mt-4 flex items-center justify-center gap-2 rounded-xl bg-sand py-3 text-xs font-semibold text-slate-600">🛵 Entrega estimada em 30–45 min</div><button id="checkout-start" class="ripple pulse-cta mt-3 w-full rounded-2xl bg-acai py-4 font-bold text-white shadow-xl shadow-acai/20">Finalizar Pedido →</button>`;
  }
  function initSwipe(){document.querySelectorAll('.swipe-content').forEach(content=>{let startX=0,delta=0,dragged=false;content.addEventListener('pointerdown',event=>{startX=event.clientX;delta=0;dragged=false;content.setPointerCapture(event.pointerId)});content.addEventListener('pointermove',event=>{if(!startX)return;delta=Math.min(0,Math.max(-90,event.clientX-startX));if(Math.abs(delta)>8)dragged=true;content.style.transition='none';content.style.transform=`translateX(${delta}px)`});content.addEventListener('pointerup',()=>{content.style.transition='';content.style.transform='';content.classList.toggle('revealed',delta<-42);content.dataset.dragged=dragged?'1':'0';setTimeout(()=>delete content.dataset.dragged,80);startX=0})})}
  function renderReorder(){const last=read(KEYS.ultimoPedido,null)||read(KEYS.last,null),banner=$('#reorder-banner');if(!last?.items?.length)return banner.classList.add('hidden');banner.classList.remove('hidden');$('#reorder-summary').textContent=last.items.slice(0,3).map(item=>`${item.quantity}x ${item.name}`).join(' • ')+(last.items.length>3?'…':'')}
  function reorderLast(){const last=read(KEYS.ultimoPedido,null)||read(KEYS.last,null);if(!last?.items?.length)return toast('Nenhum pedido anterior encontrado.','error');cart=last.items.map((item,index)=>{const product=products.find(p=>p.id===item.id)||products.find(p=>p.name===item.name);return{key:`repeat-${Date.now()}-${index}`,id:product?.id||item.id,category:product?.cat||item.category,name:item.name,img:product?.img||item.img||'assets/hero-mingus.png',unitPrice:Number(item.unitPrice),quantity:Number(item.quantity),extras:item.extras||[]}});saveCart();rewardCart();toast('Seu último pedido voltou para a sacola!');setTimeout(()=>{renderCart();openLayer(drawer)},350)}

  let sectionObserver;
  function initScrollSpy(){if(sectionObserver)sectionObserver.disconnect();sectionObserver=new IntersectionObserver(entries=>{const current=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(current){category=current.target.dataset.productSection;renderCategories()}},{rootMargin:'-150px 0px -55% 0px',threshold:[0,.25,.5]});document.querySelectorAll('[data-product-section]').forEach(section=>sectionObserver.observe(section))}
  function setupTilt(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',event=>{if(event.pointerType==='touch')return;const rect=card.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width-.5,y=(event.clientY-rect.top)/rect.height-.5;card.style.transform=`perspective(800px) rotateX(${-y*7}deg) rotateY(${x*7}deg) translateY(-4px) scale(1.02)`;card.style.setProperty('--shine-x',`${(x+.5)*100}%`);card.style.setProperty('--shine-y',`${(y+.5)*100}%`)});card.addEventListener('pointerleave',()=>card.style.transform='');card.addEventListener('pointerdown',()=>{card.classList.add('tilt-touch');setTimeout(()=>card.classList.remove('tilt-touch'),450)})})}
  function openProduct(id){editingKey=null;selected=products.find(p=>p.id===id);if(selected?.cat==='acai')return openAcaiWizard(selected);quantity=1;selections=[];productNotes='';renderProduct();openLayer(productModal)}
  function editCartItem(key){const item=cart.find(entry=>entry.key===key),product=products.find(entry=>entry.id===item?.id);if(!item||!product)return;editingKey=key;closeLayers();if(product.cat==='acai'){const baseEntry=item.extras.find(extra=>extra.name.startsWith('Base:')),extras=item.extras.filter(extra=>!extra.name.startsWith('Base:'));wizard={step:3,size:product.id,base:baseEntry?.name.replace('Base: ','')||null,extras:extras.filter(extra=>!extra.price).map(extra=>extra.name),paidExtras:extras.filter(extra=>Number(extra.price)>0)};setTimeout(()=>{renderWizard();openLayer(acaiWizard)},280)}else{selected=product;quantity=Math.max(1,item.quantity);selections=(item.extras||[]).map(extra=>({...extra}));setTimeout(()=>{renderProduct();openLayer(productModal)},280)}}
  function openAcaiWizard(){wizard={step:1,size:null,base:null,extras:[],paidExtras:[]};renderWizard();openLayer(acaiWizard)}
  function renderWizard(){
    const steps=['1. Tamanho','2. Base','3. Complementos'];$('#wizard-progress').className='grid grid-cols-3 gap-2';$('#wizard-progress').innerHTML=steps.map((label,index)=>`<div><i class="block h-1.5 rounded-full ${index<wizard.step?'bg-acai':'bg-slate-100'}"></i><span class="mt-1.5 block text-[9px] font-bold uppercase tracking-wider ${index+1===wizard.step?'text-acai':'text-slate-400'}">${label}</span></div>`).join('');
    if(wizard.step===1){const sizes=products.filter(p=>p.cat==='acai'),hints={a300:['Só um refresco','1 pessoa'],a500:['Escolha sem erro','1 pessoa'],a700:['Fome grande','1–2 pessoas'],a1l:['Para compartilhar','2–3 pessoas']};$('#wizard-body').innerHTML=`<div class="wizard-panel"><div class="rounded-2xl bg-teal/5 p-4"><p class="text-xs font-bold text-teal">DICA MINGOS</p><p class="mt-1 text-sm text-slate-600">Na dúvida? O <b>500 ml</b> é o favorito: mata a vontade sem pesar.</p></div><h3 class="mt-5 font-display text-2xl font-bold">Para quem é esse açaí?</h3><div class="mt-4 grid gap-3">${sizes.map(p=>{const hint=hints[p.id]||['Escolha seu tamanho',''];const recommended=p.id==='a500';return`<button data-wizard-size="${p.id}" class="relative flex items-center gap-4 rounded-2xl border p-3 text-left transition ${wizard.size===p.id?'border-acai bg-acai/5 ring-4 ring-acai/5':'border-black/10 hover:border-acai/30'}">${recommended?'<span class="absolute -top-2 right-3 rounded-full bg-gold px-2 py-1 text-[9px] font-bold uppercase text-white">Mais pedido</span>':''}<img src="${esc(p.img)}" alt="" class="h-16 w-16 rounded-xl object-cover"><span class="min-w-0 flex-1"><small class="text-xs font-semibold text-teal">${hint[0]} • ${hint[1]}</small><b class="mt-0.5 block font-display text-base">${esc(p.name)}</b><strong class="text-sm text-gold">${money(p.price)}</strong></span><i class="grid h-7 w-7 place-items-center rounded-full border ${wizard.size===p.id?'border-acai bg-acai text-white':'border-black/10'}">${wizard.size===p.id?'✓':''}</i></button>`}).join('')}</div></div>`}
    if(wizard.step===2){const product=products.find(p=>p.id===wizard.size),extras=['Banana','Morango','Granola','Leite em pó','Paçoca','Coco ralado'];$('#wizard-body').innerHTML=`<div class="wizard-panel"><div class="flex items-center gap-3 rounded-2xl bg-sand p-3"><img src="${esc(product.img)}" alt="" class="h-14 w-14 rounded-xl object-cover"><div><small class="text-xs text-slate-400">Você escolheu</small><b class="block font-display">${esc(product.name)} • ${money(product.price)}</b></div><button id="change-size" class="ml-auto text-xs font-bold text-acai">Trocar</button></div><h3 class="mt-5 font-display text-xl font-bold">Escolha a base</h3><div class="mt-3 grid grid-cols-3 gap-2">${['Tradicional','Com banana','Zero açúcar'].map(base=>`<button data-wizard-base="${base}" class="rounded-xl border px-2 py-3 text-xs font-semibold transition ${wizard.base===base?'border-acai bg-acai/5 text-acai':'border-black/10'}">${wizard.base===base?'✓ ':''}${base}</button>`).join('')}</div><div class="mt-6 flex items-end justify-between"><div><h3 class="font-display text-xl font-bold">Adicionais</h3><p class="text-xs text-slate-500">Até 4 inclusos</p></div><b class="text-sm text-teal">${wizard.extras.length}/4</b></div><div class="mt-3 grid grid-cols-2 gap-2">${extras.map(name=>`<button data-wizard-extra="${name}" class="rounded-xl border px-3 py-3 text-sm font-semibold transition ${wizard.extras.includes(name)?'border-teal bg-teal/5 text-teal':'border-black/10'}">${wizard.extras.includes(name)?'✓ ':''}${name}</button>`).join('')}</div></div>`}
    if(wizard.step===2)$('#wizard-body').innerHTML=`<div id="wizard-required" class="wizard-panel rounded-2xl p-1"><h3 class="font-display text-2xl font-bold">Qual base você prefere?</h3><p class="mt-2 text-sm text-slate-500">Escolha uma opção para continuar.</p><div class="mt-5 grid gap-3">${['Açaí Tradicional','Açaí com Cupuaçu','Creme de Pitaya'].map(base=>`<button data-wizard-base="${base}" class="min-h-14 rounded-2xl border px-4 text-left font-semibold ${wizard.base===base?'border-acai bg-acai/5 text-acai':'border-black/10'}">${wizard.base===base?'✓ ':''}${base}</button>`).join('')}</div></div>`;
    if(wizard.step===3){const free=['Leite em pó','Granola','Paçoca'],paid=[['Nutella',5],['Morango',4],['Ouro Branco',4.5]],product=products.find(p=>p.id===wizard.size);$('#wizard-body').innerHTML=`<div class="wizard-panel"><h3 class="font-display text-2xl font-bold">Finalize do seu jeito</h3><p class="mt-1 text-sm text-slate-500">Gratuitos: escolha até 3.</p><div class="mt-4 grid grid-cols-2 gap-2">${free.map(name=>`<button data-wizard-extra="${name}" class="min-h-12 rounded-xl border px-3 text-sm font-semibold ${wizard.extras.includes(name)?'border-teal bg-teal/5 text-teal':'border-black/10'}">${wizard.extras.includes(name)?'✓ ':''}${name}</button>`).join('')}</div><h4 class="mt-6 font-display font-bold">Adicionais pagos</h4><div class="mt-3 grid gap-2">${paid.map(([name,price])=>`<button data-wizard-paid="${name}" data-price="${price}" class="flex min-h-12 items-center justify-between rounded-xl border px-4 text-sm font-semibold ${wizard.paidExtras.some(x=>x.name===name)?'border-acai bg-acai/5 text-acai':'border-black/10'}"><span>${wizard.paidExtras.some(x=>x.name===name)?'✓ ':''}${name}</span><b>+ ${money(price)}</b></button>`).join('')}</div></div>`}
    const product=products.find(p=>p.id===wizard.size),wizardTotal=fromCents(cents(product?.price||0)+wizard.paidExtras.reduce((s,x)=>s+cents(x.price),0));$('#wizard-footer').innerHTML=`${wizard.step>1?'<button id="wizard-back" class="min-h-12 rounded-2xl border border-black/10 px-5 font-semibold">Voltar</button>':''}<button id="wizard-next" class="ripple min-h-12 flex-1 rounded-2xl bg-acai px-3 font-bold text-white">${wizard.step===3?`Adicionar à Sacola • ${money(wizardTotal)}`:'Avançar'}</button>`;
  }
  function finishWizard(){if(!wizard.size||!wizard.base){wizard.step=wizard.size?2:1;renderWizard();$('#wizard-required')?.classList.add('wizard-error');return toast(`Escolha ${wizard.size?'uma base':'um tamanho'} para continuar.`,'error')}const product=products.find(p=>p.id===wizard.size),paid=wizard.paidExtras.reduce((s,x)=>s+cents(x.price),0),data={id:product.id,category:'acai',name:product.name,img:product.img,unitPrice:fromCents(cents(product.price)+paid),quantity:editingKey?Math.max(1,cart.find(item=>item.key===editingKey)?.quantity||1):1,extras:[{name:`Base: ${wizard.base}`,price:0},...wizard.extras.map(name=>({name,price:0})),...wizard.paidExtras]};if(editingKey){cart=cart.map(item=>item.key===editingKey?{...item,...data}:item);editingKey=null;saveCart();closeLayers();toast('Açaí atualizado na sacola!')}else{cart.push({key:`${product.id}-${Date.now()}`,...data});saveCart();playSound('ice');rewardCart();showCartChoice()}}
  function showCartChoice(){closeLayers();toast('Produto adicionado à sacola!');setTimeout(()=>openLayer(cartChoiceModal),280)}
  function renderProduct(){
    const options=(selected.opts||[]).map((group,groupIndex)=>`<fieldset class="mt-5"><legend class="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">${esc(group.name)} <span class="font-normal normal-case">• até ${group.max}</span></legend><div class="flex flex-wrap gap-2">${group.items.map(raw=>{const [name,price='0']=raw.split('|'),key=`${groupIndex}-${name}`,checked=selections.some(x=>x.key===key);return`<label class="option-chip cursor-pointer rounded-xl border border-black/10 px-3 py-2 text-xs font-semibold transition"><input class="sr-only" type="checkbox" data-option="${key}" data-group="${groupIndex}" data-max="${group.max}" data-name="${esc(name)}" data-price="${price}" ${checked?'checked':''}>${esc(name)} ${+price?`+${money(+price)}`:''}</label>`}).join('')}</div></fieldset>`).join('');
    $('#product-detail').innerHTML=`<div class="grid md:grid-cols-[.9fr_1.1fr]"><img src="${esc(selected.img)}" alt="${esc(selected.name)}" class="h-64 w-full object-cover md:h-full md:min-h-[520px]"><div class="p-5 sm:p-8"><span class="rounded-full bg-acai/5 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-acai">${esc(selected.tag||selected.cat)}</span><h2 class="mt-4 font-display text-3xl font-bold tracking-tight">${esc(selected.name)}</h2><p class="mt-2 text-sm leading-6 text-slate-500">${esc(selected.desc)}</p>${options}${selected.cat==='pasteis'?`<label class="mt-5 block text-xs font-bold text-slate-500">OBSERVAÇÕES<textarea id="product-notes" maxlength="120" rows="2" class="mt-2 w-full rounded-xl border border-black/10 bg-sand p-3 text-sm" placeholder="Ex.: bem frito">${esc(productNotes)}</textarea></label>`:''}<div class="sticky bottom-0 mt-7 flex gap-3 bg-white/95 py-3 backdrop-blur"><div class="flex items-center rounded-2xl bg-sand p-1"><button data-product-qty="-1" class="h-11 w-10 rounded-xl bg-white font-bold">−</button><b class="w-8 text-center">${quantity}</b><button data-product-qty="1" class="h-11 w-10 rounded-xl bg-white font-bold">+</button></div><button id="add-product" class="ripple flex-1 rounded-2xl bg-acai px-4 font-bold text-white">Adicionar • ${money(fromCents((cents(selected.price)+cents(extrasTotal()))*quantity))}</button></div></div></div>`;
  }

  function requestCheckout(){if(!cart.length)return toast('Sua sacola está vazia. Escolha uma delícia primeiro!','error');if(subtotal()<18)return toast('O pedido mínimo é R$ 18.','error');const hasDrink=cart.some(item=>item.category==='bebidas'||products.find(p=>p.id===item.id)?.cat==='bebidas');if(!hasDrink&&!skipUpsell){closeLayers();return setTimeout(()=>openLayer(upsellModal),280)}proceedCheckout()}
  function proceedCheckout(){renderCheckout();closeLayers();setTimeout(()=>openLayer(checkoutModal),280)}
  const input=(name,label,placeholder,type='text')=>`<label class="block text-xs font-semibold text-slate-600">${label}<input name="${name}" type="${type}" value="${esc(checkout[name])}" placeholder="${placeholder}" required class="mt-1.5 w-full rounded-xl border border-black/10 bg-sand px-4 py-3 text-sm outline-none focus:border-acai focus:ring-4 focus:ring-acai/5"></label>`;
  function changeText(){const paid=Number(String(checkout.changeFor).replace(',','.'));if(!paid)return'Informe o valor para calcular o troco.';return paid<total()?`Faltam ${money(total()-paid)}.`:`Seu troco será ${money(paid-total())}.`}
  function renderCheckout(){
    $('#checkout-body').innerHTML=`<div class="grid grid-cols-2 gap-2"><label class="option-chip rounded-2xl border p-4"><input type="radio" name="mode" value="delivery" ${checkout.mode==='delivery'?'checked':''} class="mr-2 accent-acai"><b class="text-sm">Entrega</b><small class="mt-1 block text-slate-500">25–40 min</small></label><label class="option-chip rounded-2xl border p-4"><input type="radio" name="mode" value="pickup" ${checkout.mode==='pickup'?'checked':''} class="mr-2 accent-acai"><b class="text-sm">Retirada</b><small class="mt-1 block text-slate-500">15–25 min</small></label></div><div class="grid gap-3 sm:grid-cols-2">${input('name','Seu nome','Como podemos chamar você?')}${input('phone','WhatsApp','(51) 99999-9999','tel')}${checkout.mode==='delivery'?`${input('neighborhood','Bairro','Ex.: Centro')}<div class="sm:col-span-2">${input('street','Rua / Avenida','Nome da rua')}</div>${input('number','Número','123')}${input('city','Cidade','Tramandaí / RS')}`:''}</div><div><p class="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Pagamento na entrega</p><div class="grid grid-cols-3 gap-2">${[['card','Cartão'],['pix','Pix'],['cash','Dinheiro']].map(([id,label])=>`<label class="option-chip rounded-xl border p-3 text-center text-xs font-bold"><input type="radio" name="payment" value="${id}" ${checkout.payment===id?'checked':''} class="sr-only">${label}</label>`).join('')}</div></div>${checkout.payment==='cash'?`<div>${input('changeFor','Troco para quanto?','Ex.: 100,00')}<p id="change-result" class="mt-2 rounded-xl bg-teal/5 p-3 text-xs font-semibold text-teal">${changeText()}</p></div>`:''}<label class="block text-xs font-semibold text-slate-600">Observações<textarea name="notes" rows="2" class="mt-1.5 w-full rounded-xl border border-black/10 bg-sand px-4 py-3 text-sm outline-none" placeholder="Interfone, ponto de referência...">${esc(checkout.notes)}</textarea></label>`;
    $('#checkout-footer').innerHTML=`<div class="mb-3 flex items-center justify-between"><span class="text-sm text-slate-500">Total do pedido</span><b class="font-display text-xl text-acai">${money(total())}</b></div><button class="ripple w-full rounded-2xl bg-acai py-4 font-bold text-white shadow-xl shadow-acai/20">Confirmar Pedido</button>`;
  }
  async function finishOrder(){
    if(checkoutLocked)return toast('Seu pedido já está sendo enviado.','error');if(!cart.length)return toast('Sua sacola está vazia.','error');const required=['name','phone',...(checkout.mode==='delivery'?['neighborhood','street','number','city']:[])],invalid=required.filter(name=>!String(checkout[name]||'').trim());document.querySelectorAll('[name]').forEach(el=>el.classList.toggle('field-error',invalid.includes(el.name)));if(invalid.length)return toast('Preencha corretamente os campos destacados.','error');checkoutLocked=true;const submit=$('#checkout-form button[type="submit"],#checkout-footer button');if(submit){submit.disabled=true;submit.textContent='Enviando pedido…'}
    const order={id:`ord-${Date.now()}`,code:`MG${String(Date.now()).slice(-5)}`,createdAt:new Date().toISOString(),status:'received',customer:{name:checkout.name,phone:checkout.phone},deliveryMode:checkout.mode,address:{street:checkout.street,number:checkout.number,neighborhood:checkout.neighborhood,city:checkout.city},payment:{method:checkout.payment,changeFor:checkout.changeFor},notes:checkout.notes,items:cart.map(i=>({id:i.id,category:i.category,name:i.name,img:i.img,quantity:i.quantity,unitPrice:i.unitPrice,extras:i.extras})),subtotal:subtotal(),discount:discount(),deliveryFee:deliveryFee(),total:total()};
    const message=[`🍇 *NOVO PEDIDO MINGOS*`,`Pedido: #${order.code}`,'',...order.items.map(item=>`• ${item.quantity}x ${item.name} — ${money(item.unitPrice*item.quantity)}${item.extras?.length?`\n  ↳ ${item.extras.map(extra=>extra.name).join(', ')}`:''}`),'',`Subtotal: ${money(order.subtotal)}`,order.discount?`Desconto: -${money(order.discount)}`:'',`Entrega: ${order.deliveryFee?money(order.deliveryFee):'Grátis'}`,`*TOTAL: ${money(order.total)}*`,'',`Cliente: ${order.customer.name}`,`WhatsApp: ${order.customer.phone}`,order.deliveryMode==='delivery'?`Endereço: ${order.address.street}, ${order.address.number} — ${order.address.neighborhood} — ${order.address.city}`:'Modalidade: Retirada no balcão',`Pagamento: ${{card:'Cartão',pix:'Pix',cash:'Dinheiro'}[order.payment.method]}`,order.payment.method==='cash'&&order.payment.changeFor?`Troco para: R$ ${order.payment.changeFor}`:'',order.notes?`Observações: ${order.notes}`:''].filter(Boolean).join('\n');
    try{const saved=await window.MingosSync.createOrder(order);write(KEYS.ultimoPedido,saved);cart=[];coupon=null;saveCart();closeLayers();celebrate();toast('Pedido confirmado no sistema! Abrindo o WhatsApp...');window.MingosTracking?.show(saved);setTimeout(()=>{window.open(`https://wa.me/5545991375964?text=${encodeURIComponent(message)}`,'_blank','noopener')},900)}catch(error){checkoutLocked=false;if(submit){submit.disabled=false;submit.textContent='Confirmar Pedido'}console.error(error);toast(error.friendlyMessage||'Não foi possível registrar o pedido. Tente novamente.','error')}
  }

  document.addEventListener('click',event=>{
    const target=event.target.closest('button,a,[data-product-card],[data-edit-cart]');if(!target)return;
    if(target.matches('.ripple')){const circle=document.createElement('span'),rect=target.getBoundingClientRect(),size=Math.max(rect.width,rect.height);circle.className='ripple-dot';circle.style.cssText=`width:${size}px;height:${size}px;left:${event.clientX-rect.left-size/2}px;top:${event.clientY-rect.top-size/2}px`;target.appendChild(circle);setTimeout(()=>circle.remove(),600)}
    if(target.dataset.close!==undefined)closeLayers();
    if(target.id==='cart-open'||target.id==='mobile-cart'){renderCart();openLayer(drawer)}
    if(target.id==='login-open'||target.id==='footer-login')openLayer(loginModal);
    if(target.dataset.category){category=target.dataset.category;renderCategories();const destination=category==='all'?$('#cardapio'):$(`#category-${category}`);destination?.scrollIntoView({behavior:'smooth',block:'start'})}
    if(target.dataset.categoryJump){category=target.dataset.categoryJump;renderCategories();setTimeout(()=>$(`#category-${category}`)?.scrollIntoView({behavior:'smooth',block:'start'}),50)}
    if(target.dataset.product)openProduct(target.dataset.product);
    if(target.dataset.quickAdd){const product=products.find(item=>item.id===target.dataset.quickAdd);cart.push({key:`${product.id}-${Date.now()}`,id:product.id,category:product.cat,name:product.name,img:product.img,unitPrice:product.price,quantity:1,extras:[]});saveCart();playSound('ice');rewardCart();showCartChoice()}
    const card=target.closest('[data-product-card]');if(card&&!target.matches('[data-product],[data-quick-add]'))openProduct(card.dataset.productCard);
    if(target.dataset.productQty){quantity=Math.max(1,quantity+Number(target.dataset.productQty));renderProduct()}
    if(target.id==='add-product'){const extras=[...selections,...(productNotes.trim()?[{name:`Observação: ${productNotes.trim()}`,price:0}]:[])],data={id:selected.id,category:selected.cat,name:selected.name,img:selected.img,unitPrice:fromCents(cents(selected.price)+cents(extrasTotal())),quantity:Math.max(1,Math.trunc(quantity)),extras};if(editingKey){cart=cart.map(item=>item.key===editingKey?{...item,...data}:item);editingKey=null;saveCart();closeLayers();toast('Produto atualizado na sacola!')}else{cart.push({key:`${selected.id}-${Date.now()}`,...data});saveCart();playSound(selected.cat==='pasteis'?'croc':'ice');rewardCart();showCartChoice()}}
    if(target.dataset.cart){const item=cart.find(i=>i.key===target.dataset.cart);if(item){item.quantity+=Number(target.dataset.qty);if(item.quantity<=0)cart=cart.filter(i=>i.key!==item.key);saveCart()}}
    if(target.dataset.removeCart){cart=cart.filter(item=>item.key!==target.dataset.removeCart);saveCart();toast('Item removido da sacola.')}
    if(target.id==='clear-cart'&&cart.length){cart=[];coupon=null;saveCart();toast('Sacola esvaziada.')}
    const editable=target.closest('[data-edit-cart]');if(editable&&!target.closest('[data-cart]')&&editable.dataset.dragged!=='1')editCartItem(editable.dataset.editCart);
    if(target.id==='apply-coupon'){const value=$('#coupon-input').value.trim().toUpperCase();coupon=value==='MINGOS10'?{code:value}:null;toast(coupon?'Cupom aplicado!':'Cupom inválido. Tente MINGOS10.');renderCart()}
    if(target.id==='checkout-start')requestCheckout();
    if(target.dataset.wizardSize){wizard.size=target.dataset.wizardSize;renderWizard()}
    if(target.dataset.wizardBase){wizard.base=target.dataset.wizardBase;renderWizard()}
    if(target.dataset.wizardExtra){const name=target.dataset.wizardExtra;if(wizard.extras.includes(name))wizard.extras=wizard.extras.filter(item=>item!==name);else if(wizard.extras.length<3)wizard.extras.push(name);else return toast('Escolha até 3 complementos gratuitos.','error');renderWizard()}
    if(target.dataset.wizardPaid){const name=target.dataset.wizardPaid,price=Number(target.dataset.price),has=wizard.paidExtras.some(x=>x.name===name);wizard.paidExtras=has?wizard.paidExtras.filter(x=>x.name!==name):[...wizard.paidExtras,{name,price}];renderWizard()}
    if(target.id==='wizard-back'){wizard.step=Math.max(1,wizard.step-1);renderWizard()}if(target.id==='change-size'){wizard.step=1;renderWizard()}
    if(target.id==='wizard-next'){if(wizard.step===1&&!wizard.size){$('#wizard-body').classList.add('wizard-error');return toast('Escolha o tamanho do seu açaí.','error')}if(wizard.step===2&&!wizard.base){$('#wizard-required')?.classList.add('wizard-error');return toast('Escolha uma base para continuar.','error')}if(wizard.step<3){wizard.step++;renderWizard()}else finishWizard()}
    if(target.id==='go-to-cart'){closeLayers();setTimeout(()=>{renderCart();openLayer(drawer)},280)}
    if(target.id==='continue-shopping'){closeLayers();setTimeout(()=>$(`#category-${category==='all'?'acai':category}`)?.scrollIntoView({behavior:'smooth',block:'start'}),280)}
    if(target.dataset.mood){mood=target.dataset.mood;document.querySelectorAll('[data-mood]').forEach(button=>button.classList.toggle('mood-on',button.dataset.mood===mood));renderProducts()}
    if(target.id==='choose-drink'){skipUpsell=true;closeLayers();category='bebidas';renderCategories();setTimeout(()=>$(`#category-bebidas`)?.scrollIntoView({behavior:'smooth',block:'start'}),280)}
    if(target.id==='skip-drink'){skipUpsell=true;closeLayers();setTimeout(proceedCheckout,280)}
    if(target.id==='track-order'){const last=read(KEYS.last,null),updated=last&&read(KEYS.orders,[]).find(o=>o.id===last.id);if(updated||last)window.MingosTracking?.show(updated||last);else toast('Você ainda não fez um pedido.')}
    if(target.id==='signup-link')toast('Cadastro demonstrativo: use qualquer e-mail para entrar.')
    if(target.id==='reorder-button')reorderLast();
    if(target.id==='sound-toggle'){muted=!muted;write(KEYS.muted,muted);target.textContent=muted?'🔇 Sons desligados':'🔊 Sons ligados';target.setAttribute('aria-pressed',String(muted));if(!muted)playSound('ice')}
  });
  $('#product-detail').addEventListener('change',event=>{const input=event.target.closest('[data-option]');if(!input)return;const group=input.dataset.group,key=input.dataset.option;if(input.checked){const same=selections.filter(x=>x.group===group);if(same.length>=Number(input.dataset.max)){input.checked=false;return toast(`Escolha até ${input.dataset.max}.`)}selections.push({key,group,name:input.dataset.name,price:Number(input.dataset.price)})}else selections=selections.filter(x=>x.key!==key);renderProduct()});
  $('#product-detail').addEventListener('input',event=>{if(event.target.id==='product-notes')productNotes=event.target.value});
  $('#search').addEventListener('input',event=>{search=event.target.value;renderProducts()});
  $('#checkout-body').addEventListener('input',event=>{if(event.target.name){checkout[event.target.name]=event.target.value;if(event.target.name==='changeFor')$('#change-result').textContent=changeText()}});
  $('#checkout-body').addEventListener('change',event=>{if(['mode','payment'].includes(event.target.name)){checkout[event.target.name]=event.target.value;renderCheckout()}});
  $('#checkout-form').addEventListener('submit',event=>{event.preventDefault();finishOrder()});
  $('#login-form').addEventListener('submit',event=>{event.preventDefault();write(KEYS.user,{email:event.target.querySelector('input[type=email]').value});closeLayers();toast('Login realizado com sucesso!')});
  overlay.addEventListener('click',closeLayers);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeLayers()});
  window.addEventListener('storage',event=>{if(event.key===KEYS.products){products=read(KEYS.products,defaults);renderProducts()}if(event.key===KEYS.orders){const last=read(KEYS.last,null),updated=last&&read(KEYS.orders,[]).find(order=>order.id===last.id);if(updated&&last&&updated.status!==last.status){write(KEYS.last,updated);toast('Seu pedido foi atualizado!')}}});
  window.addEventListener('mingos:sync',event=>{if(event.detail.key===KEYS.products){products=read(KEYS.products,defaults);renderProducts()}});
  function showActivity(){const recent=read(KEYS.orders,[]).filter(order=>order.items?.length).slice(0,8);if(recent.length){const order=recent[Math.floor(Math.random()*recent.length)],item=order.items[Math.floor(Math.random()*order.items.length)];toast(`Pedido recente: ${item.quantity}x ${item.name} 💜`)}else toast('Dica Mingos: o Açaí 500 ml é o favorito da casa. 🌊')}
  renderCategories();renderSkeleton();renderCart();renderReorder();setupParallax();const soundButton=$('#sound-toggle');soundButton.textContent=muted?'🔇 Sons desligados':'🔊 Sons ligados';soundButton.setAttribute('aria-pressed',String(muted));setTimeout(renderProducts,1500);setTimeout(showActivity,45000);setInterval(showActivity,150000);
  function renderFlash(){const f=activeFlash(),banner=$('#flash-banner');if(!f){banner.classList.add('hidden');return}banner.classList.remove('hidden');$('#flash-title').textContent=f.title;$('#flash-copy').textContent=f.message;const left=Math.max(0,f.expiresAt-Date.now());$('#flash-countdown').textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.floor(left/1000)%60).padStart(2,'0')}`;if(!left){localStorage.removeItem(KEYS.flash);banner.classList.add('hidden')}}
  window.addEventListener('storage',event=>{if(event.key===KEYS.flash){renderFlash();renderCart()}});setupCarousel();renderFlash();setInterval(renderFlash,1000);
  window.addEventListener('mingos:backend-status',event=>{const badge=$('#backend-status'),state=event.detail.state;badge.textContent=state==='online'?'● Online':state==='error'?'● Erro no sistema':state==='offline'?'● Modo offline':'● Conectando';badge.className=`hidden rounded-full px-2.5 py-1 text-[10px] font-bold shadow-sm sm:inline-flex ${state==='online'?'bg-teal/10 text-teal':state==='error'?'bg-red-50 text-red-600':'bg-white text-slate-500'}`});
  (async()=>{try{const firebase=await window.MingosSync.waitFirebase();await firebase.anonymousUser();firebase.watchCollection('products',next=>{if(next.length){products=next.map(product=>({...product,img:contextualImages[product.id]||product.img}));write(KEYS.products,products);renderProducts()}});firebase.watchCollection('settings',next=>{next.forEach(setting=>{if(setting.id==='flash')write(KEYS.flash,setting.value)});renderFlash();renderCart()})}catch(error){console.error('Firebase indisponível:',error);toast('Modo offline: o cardápio continua disponível.','error')}})();
})();
