import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import {getAuth,setPersistence,browserLocalPersistence,signInAnonymously,signInWithEmailAndPassword,createUserWithEmailAndPassword,linkWithCredential,EmailAuthProvider,sendPasswordResetEmail,updateProfile,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import {initializeFirestore,persistentLocalCache,persistentMultipleTabManager,collection,doc,setDoc,addDoc,updateDoc,deleteDoc,getDocFromServer,getDocs,onSnapshot,orderBy,query,where,writeBatch,waitForPendingWrites,serverTimestamp,runTransaction} from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyBw0mc9z57cvG3ieJWBwUTjJj4FdR7PWxw',authDomain:'mingosfood-b0ef0.firebaseapp.com',projectId:'mingosfood-b0ef0',storageBucket:'mingosfood-b0ef0.firebasestorage.app',messagingSenderId:'927616413219',appId:'1:927616413219:web:6bf3ff605b733288fa0b96'};
const ADMIN_UID='HyAvEp5TLfh414rAykVQTwxWjrS2';
const app=initializeApp(firebaseConfig),auth=getAuth(app);
const db=initializeFirestore(app,{experimentalAutoDetectLongPolling:true,localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})});
const clean=value=>JSON.parse(JSON.stringify(value));
const status=(state,detail='')=>window.dispatchEvent(new CustomEvent('mingos:backend-status',{detail:{state,detail}}));

await setPersistence(auth,browserLocalPersistence);
function currentAuth(){if(auth.currentUser)return Promise.resolve(auth.currentUser);return new Promise(resolve=>{let stop;stop=onAuthStateChanged(auth,user=>{stop?.();resolve(user)})})}
async function anonymousUser(){const current=await currentAuth();if(current)return current;status('connecting','Autenticando cliente');const user=(await signInAnonymously(auth)).user;status('online','Cliente conectado');return user}
async function customerSignup({name,email,password,phone}){const safeName=String(name||'').trim().replace(/\s+/g,' '),safeEmail=String(email||'').trim().toLowerCase(),digits=String(phone||'').replace(/\D/g,'');if(safeName.length<2)throw new Error('Informe seu nome.');if(digits.length<10||digits.length>11)throw new Error('Informe um WhatsApp com DDD.');if(String(password||'').length<6)throw new Error('A senha precisa ter pelo menos 6 caracteres.');let user=await currentAuth();const credential=EmailAuthProvider.credential(safeEmail,password);if(user?.isAnonymous)user=(await linkWithCredential(user,credential)).user;else if(!user)user=(await createUserWithEmailAndPassword(auth,safeEmail,password)).user;else throw new Error('Saia da conta atual para criar outra.');await updateProfile(user,{displayName:safeName});await setDoc(doc(db,'users',user.uid),clean({uid:user.uid,name:safeName,email:safeEmail,phone:digits,role:'customer',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}),{merge:true});return user}
async function customerLogin(email,password){return(await signInWithEmailAndPassword(auth,email,password)).user}
async function resetPassword(email){await sendPasswordResetEmail(auth,email)}
function watchAuth(callback){return onAuthStateChanged(auth,callback)}
async function adminLogin(email,password){status('connecting','Validando administrador');const result=await signInWithEmailAndPassword(auth,email,password);if(result.user.uid!==ADMIN_UID){await signOut(auth);throw Object.assign(new Error('Conta sem permissão administrativa.'),{code:'mingos/not-admin'})}status('online','Painel conectado');return result.user}
async function createOrder(order){const user=await anonymousUser(),ref=doc(collection(db,'orders')),id=ref.id,now=new Date().toISOString(),payload=clean({...order,id,code:`MG${id.slice(-6).toUpperCase()}`,ownerUid:user.uid,status:'pending_acceptance',acceptanceDeadline:new Date(Date.now()+10*60000).toISOString(),createdAt:order.createdAt||now,updatedAt:now,schemaVersion:2});status('saving','Enviando pedido à cozinha');await setDoc(ref,payload);await waitForPendingWrites(db);const confirmed=await getDocFromServer(ref);if(!confirmed.exists())throw Object.assign(new Error('O pedido não foi confirmado pelo servidor.'),{code:'mingos/not-confirmed'});status('online','Pedido enviado à cozinha');return{id:confirmed.id,...confirmed.data()}}
function watchOrder(id,callback,error=console.error){return onSnapshot(doc(db,'orders',String(id)),{includeMetadataChanges:true},snapshot=>{if(snapshot.exists()&&!snapshot.metadata.hasPendingWrites){status('online','Pedido sincronizado');callback({id:snapshot.id,...snapshot.data()})}},cause=>{status('error',cause.code||cause.message);error(cause)})}
function watchOrders(callback,error=console.error){return onSnapshot(query(collection(db,'orders'),orderBy('createdAt','desc')),{includeMetadataChanges:true},snapshot=>{status(snapshot.metadata.fromCache?'offline':'online',snapshot.metadata.fromCache?'Exibindo dados em cache':'Pedidos sincronizados');callback(snapshot.docs.map(item=>({id:item.id,...item.data()})).filter(item=>item.archived!==true))},cause=>{status('error',cause.code||cause.message);error(cause)})}
async function updateOrderStatus(id,nextStatus,extra={}){if(!['pending_acceptance','accepted','preparing','ready','delivering','completed','rejected','cancelled','expired'].includes(nextStatus))throw new Error('Status inválido.');const ref=doc(db,'orders',String(id)),now=new Date().toISOString(),timestamps={};if(nextStatus==='accepted')timestamps.acceptedAt=now;if(nextStatus==='completed')timestamps.completedAt=now;const changes=clean({status:nextStatus,updatedAt:now,...extra,...timestamps}),result=await runTransaction(db,async transaction=>{const before=await transaction.get(ref);if(!before.exists())throw new Error('Pedido não encontrado.');const current=before.data(),terminal=['completed','rejected','cancelled','expired'];if(terminal.includes(current.status)&&current.status!==nextStatus)throw new Error('Este pedido já foi finalizado e não pode mudar de status.');if(current.status==='pending_acceptance'&&new Date(current.acceptanceDeadline).getTime()<=Date.now()&&nextStatus==='accepted')throw new Error('O prazo de aceite deste pedido expirou.');transaction.update(ref,changes);return{id:String(id),...current,...changes}});await waitForPendingWrites(db);return result}
function watchMessages(orderId,callback,error=console.error){return onSnapshot(query(collection(db,'orders',String(orderId),'messages'),orderBy('createdAt','asc')),snapshot=>callback(snapshot.docs.map(item=>({id:item.id,...item.data()}))),error)}
async function sendMessage(orderId,text,role='customer'){const user=await currentAuth();if(!user)throw new Error('Entre para enviar mensagens.');const value=String(text||'').trim().slice(0,500);if(!value)throw new Error('Digite uma mensagem.');await addDoc(collection(db,'orders',String(orderId),'messages'),{senderUid:user.uid,senderName:user.displayName||(role==='admin'?'Mingos':'Cliente'),senderRole:role,text:value,createdAt:serverTimestamp()});await updateDoc(doc(db,'orders',String(orderId)),role==='admin'?{unreadCustomer:true,updatedAt:new Date().toISOString()}:{unreadAdmin:true,updatedAt:new Date().toISOString()})}
async function markOrderRead(id,role='admin'){await updateDoc(doc(db,'orders',String(id)),role==='admin'?{unreadAdmin:false,updatedAt:new Date().toISOString()}:{unreadCustomer:false,updatedAt:new Date().toISOString()})}
function watchCustomerOrders(callback,error=console.error){let stopOrders=null;const stopAuth=onAuthStateChanged(auth,user=>{stopOrders?.();stopOrders=null;if(!user)return callback([]);stopOrders=onSnapshot(query(collection(db,'orders'),where('ownerUid','==',user.uid)),snapshot=>callback(snapshot.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))),error)});return()=>{stopOrders?.();stopAuth()}}
async function saveLead({name,phone,consent}){const user=await anonymousUser(),digits=String(phone||'').replace(/\D/g,'');if(digits.length<10||digits.length>11)throw new Error('Informe um WhatsApp com DDD.');if(!consent)throw new Error('Confirme sua participação.');const payload={id:user.uid,ownerUid:user.uid,name:String(name||'').trim().slice(0,50),phone:digits,consent:true,source:'club-popup',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await setDoc(doc(db,'leads',user.uid),payload,{merge:true});return payload}
function watchCollection(name,callback,error=console.error){return onSnapshot(collection(db,name),{includeMetadataChanges:true},snapshot=>callback(snapshot.docs.map(item=>({id:item.id,...item.data()})),{fromCache:snapshot.metadata.fromCache,hasPendingWrites:snapshot.metadata.hasPendingWrites}),error)}
async function saveDocument(group,id,data){const ref=doc(db,group,String(id));if(group==='orders'&&Object.prototype.hasOwnProperty.call(data,'unreadAdmin'))await updateDoc(ref,{unreadAdmin:Boolean(data.unreadAdmin),updatedAt:new Date().toISOString()});else await setDoc(ref,clean(data),{merge:true});await waitForPendingWrites(db);return data}
async function patchDocument(group,id,data){await updateDoc(doc(db,group,String(id)),clean(data));await waitForPendingWrites(db);return data}
async function removeDocument(group,id){await deleteDoc(doc(db,group,String(id)));await waitForPendingWrites(db)}
async function clearOrders(){const snapshot=await getDocs(collection(db,'orders')),finished=snapshot.docs.filter(item=>item.data().archived!==true&&['completed','rejected','cancelled','expired'].includes(item.data().status)),archivedAt=new Date().toISOString();for(let offset=0;offset<finished.length;offset+=450){const batch=writeBatch(db);finished.slice(offset,offset+450).forEach(item=>batch.update(item.ref,{archived:true,archivedAt,updatedAt:archivedAt}));await batch.commit()}await waitForPendingWrites(db)}
function friendlyError(error){const messages={'auth/invalid-credential':'E-mail ou senha incorretos.','auth/email-already-in-use':'Este e-mail já possui uma conta. Use Entrar ou recupere a senha.','auth/invalid-email':'Informe um e-mail válido.','auth/weak-password':'Escolha uma senha mais forte, com pelo menos 6 caracteres.','auth/too-many-requests':'Muitas tentativas. Aguarde alguns minutos e tente novamente.','auth/operation-not-allowed':'Ative o método de autenticação no Firebase.','auth/unauthorized-domain':'O domínio do GitHub Pages não está autorizado no Firebase.','permission-denied':'As regras do Firestore bloquearam esta operação.','firestore/permission-denied':'As regras do Firestore bloquearam esta operação.','unavailable':'O Firebase está temporariamente indisponível.','mingos/not-confirmed':'O servidor não confirmou o pedido.'};return messages[error?.code]||messages[String(error?.code||'').replace(/^firestore\//,'')]||error?.message||'Falha de conexão com o Firebase.'}
window.MingosFirebase={ADMIN_UID,auth,db,anonymousUser,customerSignup,customerLogin,resetPassword,watchAuth,adminLogin,signOut:()=>signOut(auth),createOrder,watchOrder,watchOrders,watchCustomerOrders,updateOrderStatus,watchMessages,sendMessage,markOrderRead,saveLead,watchCollection,saveDocument,patchDocument,removeDocument,clearOrders,friendlyError};
status('ready','Firebase carregado');window.dispatchEvent(new CustomEvent('mingos:firebase-ready'));
