(() => {
  'use strict';
  const $=selector=>document.querySelector(selector);
  const steps=[['pending_acceptance','⌛','Enviado à cozinha'],['accepted','💜','Pedido aceito'],['preparing','👨‍🍳','Em preparo'],['ready','✨','Pronto'],['delivering','🛵','Saiu para entrega'],['completed','✓','Entregue']];
  let activeOrderId=null,unsubscribeOrder=null,unsubscribeMessages=null,currentOrder=null,expiryTimer=null,expiring=false;
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function copyFor(order){const map={pending_acceptance:'Estamos conferindo os itens e calculando o melhor tempo de preparo.',accepted:`A cozinha aceitou seu pedido. Previsão: ${order.estimateLabel||'30–45 minutos'}.`,preparing:'Suas delícias estão sendo preparadas com carinho.',ready:order.deliveryMode==='pickup'?'Seu pedido está pronto para retirada.':'Seu pedido está pronto e aguardando o entregador.',delivering:'Seu pedido deixou a Mingos e está indo até você.',completed:'Chegou! Aproveite seu momento Mingos 💜',rejected:`Não conseguimos aceitar o pedido desta vez. ${order.rejectionReason||'Nenhuma cobrança foi realizada.'}`,cancelled:'Este pedido foi cancelado.',expired:'Não conseguimos confirmar o pedido dentro do prazo. Nossa operação pode estar temporariamente indisponível ou com movimento acima do esperado. Nenhuma cobrança foi realizada.'};return map[order.status]||'Acompanhamento atualizado.'}
  function render(order){if(!order)return;if(order.status==='received')order={...order,status:'pending_acceptance'};currentOrder=order;activeOrderId=order.id;const rejected=['rejected','cancelled','expired'].includes(order.status),current=Math.max(0,steps.findIndex(([status])=>status===order.status));$('#tracking-code').innerHTML=`Pedido <b>#${escape(order.code||order.id)}</b> • atualização automática`;$('#tracking-title').textContent=order.status==='pending_acceptance'?'Pedido enviado à cozinha':rejected?'Pedido não confirmado':'Seu pedido está em andamento';$('#tracking-copy').textContent=copyFor(order);$('#tracking-waiting').classList.toggle('hidden',order.status!=='pending_acceptance');$('#tracking-stepper').classList.toggle('hidden',rejected);$('#tracking-stepper').innerHTML=steps.map(([status,icon,label],index)=>{const done=index<=current,active=index===current;return `<div class="tracking-step ${done?'is-done':''} ${active?'is-active':''}"><div class="tracking-rail"><span>${icon}</span>${index<steps.length-1?'<i></i>':''}</div><div><b>${label}</b><p>${active?copyFor(order):done?'Etapa concluída.':'Aguardando.'}</p></div></div>`}).join('');$('#confirm-delivery-open').classList.toggle('hidden',order.status!=='delivering');$('#cancel-pending-order').classList.toggle('hidden',order.status!=='pending_acceptance');$('#tracking-estimate').textContent=order.estimateLabel||'A confirmar pela cozinha'}
  function renderMessages(messages){const body=$('#order-chat-messages');body.innerHTML=messages.length?messages.map(message=>`<article class="chat-message ${message.senderRole==='customer'?'from-customer':'from-store'}"><b>${message.senderRole==='customer'?'Você':'Mingos'}</b><p>${escape(message.text)}</p><small>${message.createdAt?.toDate?message.createdAt.toDate().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'agora'}</small></article>`).join(''):'<p class="chat-empty">Envie uma mensagem se precisar complementar o endereço ou falar com a equipe.</p>';body.scrollTop=body.scrollHeight}
  async function checkExpiry(){if(expiring||currentOrder?.status!=='pending_acceptance')return;const deadline=new Date(currentOrder.acceptanceDeadline||new Date(currentOrder.createdAt).getTime()+600000).getTime(),remaining=deadline-Date.now();$('#tracking-estimate').textContent=remaining>0?`Confirmação em até ${String(Math.floor(remaining/60000)).padStart(2,'0')}:${String(Math.floor(remaining/1000)%60).padStart(2,'0')}`:'Prazo de confirmação encerrado';if(remaining<=0){expiring=true;try{render(await window.MingosSync.updateStatus(currentOrder.id,'expired'))}catch(error){console.error(error)}finally{expiring=false}}}
  async function show(order){if(!order)return;render(order);document.querySelector('main').classList.add('hidden');$('#tracking-view').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});unsubscribeOrder?.();unsubscribeMessages?.();clearInterval(expiryTimer);expiryTimer=setInterval(checkExpiry,1000);checkExpiry();try{unsubscribeOrder=await window.MingosSync.watchOrder(order.id,render);unsubscribeMessages=await window.MingosSync.watchMessages(order.id,renderMessages)}catch(error){console.error(error)}}
  function hide(){clearInterval(expiryTimer);$('#tracking-view').classList.add('hidden');document.querySelector('main').classList.remove('hidden')}
  document.addEventListener('submit',async event=>{if(event.target.id!=='order-chat-form')return;event.preventDefault();const input=$('#order-chat-input'),button=event.submitter,text=input.value.trim();if(!text)return;button.disabled=true;try{await window.MingosSync.sendMessage(activeOrderId,text,'customer');input.value=''}catch(error){console.error(error)}finally{button.disabled=false}});
  document.addEventListener('click',async event=>{if(event.target.closest('#tracking-back'))hide();if(event.target.closest('#cancel-pending-order')&&confirm('Cancelar este pedido antes do aceite da cozinha?')){try{render(await window.MingosSync.updateStatus(activeOrderId,'cancelled'))}catch(error){console.error(error)}}if(event.target.closest('#confirm-delivery-open')){document.querySelector('#overlay').classList.remove('hidden');$('#delivery-confirm-modal').classList.remove('hidden')}if(event.target.closest('#delivery-confirm-modal [data-close]')){$('#delivery-confirm-modal').classList.add('hidden');document.querySelector('#overlay').classList.add('hidden')}if(event.target.closest('#confirm-delivery')){try{render(await window.MingosSync.updateStatus(activeOrderId,'completed'))}catch(error){console.error(error)}}});
  window.MingosTracking={show,hide,render};
})();
